[package]
name = "nyaterm-native"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
hex.workspace = true
md5.workspace = true
nyaterm-domain.workspace = true
nyaterm-migration.workspace = true
nyaterm-otp.workspace = true
nyaterm-session.workspace = true
nyaterm-terminal.workspace = true
serde_json.workspace = true
sha2.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
zed_reqwest.workspace = true

[[bin]]
name = "nyaterm"
path = "src/main.rs"
