[package]
name = "nyaterm-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
migration-dashboard = []

[dependencies]
anyhow.workspace = true
dirs.workspace = true
encoding_rs.workspace = true
futures.workspace = true
gpui.workspace = true
hex.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp", "webp"] }
md5.workspace = true
nyaterm-core.workspace = true
nyaterm-legacy.workspace = true
nyaterm-otp.workspace = true
nyaterm-terminal.workspace = true
nyaterm-terminal-gpui.workspace = true
nyaterm-transport.workspace = true
nyaterm-ui.workspace = true
regex.workspace = true
rqrr = "0.9"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tracing.workspace = true
zed_reqwest.workspace = true
zip.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
