use super::*;

impl NyaTermApp {
    pub fn new(
        runtime: AppRuntime,
        stores: crate::entities::UiStoreHandles,
        cx: &mut Context<Self>,
    ) -> Self {
        let legacy = LegacyProject::new(LEGACY_ROOT);
        let inventory = nyaterm_legacy::inventory(&legacy);
        let (session_start_tx, session_start_rx) = mpsc::channel();
        let (tunnel_tx, tunnel_rx) = mpsc::channel();
        let (process_tx, process_rx) = mpsc::channel();
        let (stats_tx, stats_rx) = mpsc::channel();
        let (translate_tx, translate_rx) = mpsc::channel();
        let (update_tx, update_rx) = mpsc::channel();
        let (docker_tx, docker_rx) = mpsc::channel();
        let (transfer_tx, transfer_rx) = mpsc::channel();
        let (ai_discovery_tx, ai_discovery_rx) = mpsc::channel();
        let (ai_chat_tx, ai_chat_rx) = mpsc::channel();
        let (
            connections,
            connection_groups,
            connection_ssh_keys,
            connection_otp_entries,
            connection_saved_passwords,
            connection_saved_credentials,
            tunnels,
            tunnel_groups,
            proxies,
            proxy_groups,
            quick_commands,
            quick_command_categories,
            command_history,
            keyword_highlights,
            settings,
            store_status,
            cloud_sync_settings,
            cloud_sync_state,
            translation_settings,
            ai_settings,
            ai_session_count,
            ai_message_count,
            ai_audit_count,
        ) = match ConnectionStore::open_with_portable_key_path(
            runtime.config_dir(),
            runtime.portable_key_path().map(ToOwned::to_owned),
        ) {
            Ok(store) => {
                let path = store.db_path().display().to_string();
                match store.load_sessions() {
                    Ok(config) => {
                        let settings = store.load_app_settings_summary().unwrap_or_default();
                        let connection_groups = config.groups.clone();
                        let connection_ssh_keys = store.list_ssh_keys().unwrap_or_default();
                        let connection_otp_entries = store.list_otp_entries().unwrap_or_default();
                        let connection_saved_passwords = store.list_passwords().unwrap_or_default();
                        let connection_saved_credentials =
                            store.list_credentials().unwrap_or_default();
                        let tunnels = store.list_tunnels().unwrap_or_default();
                        let tunnel_groups = store.list_tunnel_groups().unwrap_or_default();
                        let proxies = store.list_proxies().unwrap_or_default();
                        let proxy_groups = store.list_proxy_groups().unwrap_or_default();
                        let cloud_sync_settings =
                            store.load_cloud_sync_settings().unwrap_or_default();
                        let cloud_sync_state = store.load_cloud_sync_state().unwrap_or_default();
                        let translation_settings = store
                            .load_translation_settings()
                            .unwrap_or_else(|_| TranslationSettings {
                                target_language: settings.language.clone(),
                                ..TranslationSettings::default()
                            });
                        let quick_commands = store.load_quick_commands().unwrap_or_default();
                        let command_history = store.list_command_history(64).unwrap_or_default();
                        let keyword_highlights =
                            store.load_keyword_highlights().unwrap_or_default();
                        let ai_settings = store.load_ai_settings().unwrap_or_default();
                        let (ai_session_count, ai_message_count, ai_audit_count) =
                            ai_usage_counts(&store);
                        (
                            config.connections,
                            connection_groups,
                            connection_ssh_keys,
                            connection_otp_entries,
                            connection_saved_passwords,
                            connection_saved_credentials,
                            tunnels,
                            tunnel_groups,
                            proxies,
                            proxy_groups,
                            quick_commands.commands,
                            quick_commands.categories,
                            command_history,
                            keyword_highlights,
                            settings,
                            StoreStatus {
                                path,
                                message: "redb connection store online".to_string(),
                                ready: true,
                            },
                            cloud_sync_settings,
                            cloud_sync_state,
                            translation_settings,
                            ai_settings,
                            ai_session_count,
                            ai_message_count,
                            ai_audit_count,
                        )
                    }
                    Err(error) => (
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        KeywordHighlightConfig::default(),
                        AppSettingsSummary::default(),
                        StoreStatus {
                            path,
                            message: format!("failed to load sessions: {error}"),
                            ready: false,
                        },
                        CloudSyncSettings::default(),
                        CloudSyncState::default(),
                        TranslationSettings::default(),
                        AiSettings::default(),
                        0,
                        0,
                        0,
                    ),
                }
            }
            Err(error) => (
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                KeywordHighlightConfig::default(),
                AppSettingsSummary::default(),
                StoreStatus {
                    path: runtime
                        .config_dir()
                        .join("nyaterm.redb")
                        .display()
                        .to_string(),
                    message: format!("failed to open store: {error}"),
                    ready: false,
                },
                CloudSyncSettings::default(),
                CloudSyncState::default(),
                TranslationSettings::default(),
                AiSettings::default(),
                0,
                0,
                0,
            ),
        };
        let (appearance_ui_font_options, appearance_terminal_font_options) =
            appearance_font_options(cx);
        let otp_provider = Arc::new(NativeOtpProvider::new(
            runtime.config_dir().to_path_buf(),
            runtime.portable_key_path().map(ToOwned::to_owned),
        ));
        let transfer_duplicate_policy =
            SftpDuplicatePolicy::from_legacy_value(&settings.transfer_duplicate_strategy);
        let recording_manager = Arc::new(RecordingManager::new());
        recording_manager.set_memory_limit(settings.recording_memory_limit_bytes as usize);
        let recording_write_pipeline =
            RecordingWritePipeline::spawn(Arc::clone(&recording_manager));
        let recording_writer = recording_write_pipeline.writer();
        let cloud_sync_history = read_cloud_sync_history(
            runtime.log_dir(),
            settings.diagnostics_retention_days,
            CLOUD_SYNC_HISTORY_LIMIT,
        )
        .unwrap_or_default();
        let (ai_model_draft, ai_base_url_draft) = ai_active_profile_drafts(&ai_settings);
        let left_panel_width = settings.ui_left_panel_width as f32;
        let right_panel_width = settings.ui_right_panel_width as f32;
        let transfer_panel_height = settings.ui_transfer_height as f32;
        let quick_cmd_height = settings.ui_quick_cmd_height as f32;
        let serial_send_height = settings.ui_serial_send_height as f32;
        let activity_bar_layout = ActivityBarLayoutState {
            left_top: settings.ui_activity_bar_left_top.clone(),
            left_bottom: settings.ui_activity_bar_left_bottom.clone(),
            right_top: settings.ui_activity_bar_right_top.clone(),
            right_bottom: settings.ui_activity_bar_right_bottom.clone(),
            show_labels: settings.ui_activity_bar_show_labels,
        };
        let active_left_panel = settings
            .ui_active_left_panel
            .as_deref()
            .and_then(NavItem::from_persistence_id)
            .filter(|item| {
                activity_bar_layout.side_for_entry(item.persistence_id()) == Some(PanelSide::Left)
            })
            .or_else(|| activity_bar_layout.first_panel_on_side(PanelSide::Left));
        let active_right_panel = settings
            .ui_active_right_panel
            .as_deref()
            .and_then(NavItem::from_persistence_id)
            .filter(|item| {
                activity_bar_layout.side_for_entry(item.persistence_id()) == Some(PanelSide::Right)
            })
            .or_else(|| activity_bar_layout.first_panel_on_side(PanelSide::Right));
        let left_sidebar_collapsed = settings.ui_left_panel_collapsed;
        let right_inspector_collapsed = settings.ui_right_panel_collapsed;
        let security_secrets_unlocked = !settings.has_master_password;
        let left_open_panels = settings.ui_left_open_panels.clone();
        let right_open_panels = settings.ui_right_open_panels.clone();
        let panel_stack_sizes = settings
            .ui_panel_stack_sizes
            .iter()
            .filter_map(|(key, value)| (*value > 0).then(|| (key.clone(), (*value as f32) / 1000.)))
            .collect::<HashMap<_, _>>();
        let panel_multi_open = settings.ui_panel_multi_open;
        let settings_master_password_enabled = settings.has_master_password;
        let translate_target_language = translation_settings.target_language.clone();
        let mut terminal_output_decoder = TerminalOutputDecoder::default();
        terminal_output_decoder.set_encoding(&settings.interaction_default_encoding);
        let mut terminal_screen = initial_terminal_screen();
        terminal_screen.set_encoding(&settings.interaction_default_encoding);
        let session_manager = Arc::new(SessionManager::new());
        let terminal_frame_pipeline = TerminalFramePipeline::spawn(recording_writer);
        let session_event_bridge = SessionEventBridge::spawn(
            Arc::clone(&session_manager),
            terminal_frame_pipeline.clone(),
            settings.interaction_default_encoding.clone(),
            settings.terminal_scrollback_lines.clamp(100, 100_000) as usize,
        );

        Self {
            stores,
            runtime,
            services: NativeServices::new(),
            inventory,
            connections,
            pending_saved_connection_queue: VecDeque::new(),
            connection_search_draft: String::new(),
            connection_search_focus: cx.focus_handle(),
            connection_sort_mode: ConnectionSortMode::from_setting(
                &settings.ui_saved_connections_sort_mode,
            ),
            connections_more_menu_open: false,
            connection_context_menu: None,
            connection_group_context_menu: None,
            hovered_connection_id: None,
            connection_hover_pending: None,
            connection_drop_target: None,
            ai_execution_menu_open: false,
            hovered_connection_group_id: None,
            expanded_connection_groups: connection_groups
                .iter()
                .map(|group| group.id.clone())
                .collect(),
            connection_list_offset: 0,
            connection_groups,
            connection_editor: None,
            connection_editor_window: None,
            connection_editor_focus: cx.focus_handle(),
            connection_icon_picker_open: false,
            connection_editor_menu: None,
            connection_group_editor: None,
            connection_group_editor_focus: cx.focus_handle(),
            connection_delete_confirm: None,
            connection_group_delete_confirm: None,
            connection_ssh_keys,
            connection_otp_entries,
            connection_saved_passwords,
            connection_saved_credentials,
            connection_serial_ports: Vec::new(),
            tunnels,
            tunnel_groups,
            proxies,
            proxy_groups,
            network_tab: NetworkTab::Tunnels,
            network_delete_confirm: None,
            network_group_editor: None,
            network_group_delete_confirm: None,
            network_move_picker: None,
            network_expanded_sections: HashSet::new(),
            network_tunnel_editor: None,
            network_proxy_editor: None,
            network_group_editor_focus: cx.focus_handle(),
            network_tunnel_editor_focus: cx.focus_handle(),
            network_proxy_editor_focus: cx.focus_handle(),
            selected_connection_ids: HashSet::new(),
            last_selected_connection_id: None,
            quick_commands,
            quick_command_categories,
            quick_command_search_draft: String::new(),
            command_suggestions: None,
            command_input_tracker: TerminalInputState::new(),
            command_suggestions_suppressed: false,
            pending_command_history_entry: None,
            command_suggestion_search_gen: 0,
            credential_suggestions: None,
            credential_autofill_buffer: String::new(),
            credential_autofill_recent: HashMap::new(),
            credential_autofill_pending: None,
            credential_autofill_detection_pending: false,
            credential_autofill_next_request_id: 0,
            credential_autofill_pending_request: None,
            credential_autofill_match_pipeline: CredentialAutofillMatchPipeline::spawn(),
            credential_autofill_sending: false,
            credential_prompt_input_until_ms: 0,

            quick_command_search_focus: cx.focus_handle(),
            quick_command_selected_category: "all".to_string(),
            quick_command_sort_mode: quick_command_sort_mode_from_setting(
                &settings.ui_quick_cmd_sort_mode,
            ),
            quick_command_view_mode: quick_command_view_mode_from_setting(
                &settings.ui_quick_cmd_view_mode,
            ),
            quick_command_sort_menu_open: false,
            quick_command_view_menu_open: false,
            quick_command_ai_popover_open: false,
            quick_command_ai_prompt_draft: String::new(),
            quick_command_menu: None,
            quick_command_category_menu: None,
            quick_command_editor: None,
            quick_command_window: None,
            quick_command_delete: None,
            quick_command_details: None,
            quick_command_category_delete: None,
            quick_command_category_rename: None,
            quick_command_variable_prompt: None,
            quick_command_import_dialog_open: false,
            quick_command_import_path_prompt: None,
            quick_command_editor_focus: cx.focus_handle(),
            quick_command_details_focus: cx.focus_handle(),
            quick_command_category_rename_focus: cx.focus_handle(),
            quick_command_variable_focus: cx.focus_handle(),
            quick_command_import_focus: cx.focus_handle(),
            quick_command_ai_focus: cx.focus_handle(),
            command_history,
            session_command_history: HashMap::new(),
            command_search_draft: String::new(),
            command_search_focus: cx.focus_handle(),
            active_sessions_search_draft: String::new(),
            active_sessions_search_focus: cx.focus_handle(),
            active_session_menu: None,
            active_session_busy_actions: HashMap::new(),
            quick_switch_open: false,
            quick_switch_query: String::new(),
            quick_switch_selected_index: 0,
            quick_switch_focus: cx.focus_handle(),
            terminal_search_open: false,
            terminal_search_query: String::new(),
            terminal_search_focus: cx.focus_handle(),
            terminal_search_mode: TerminalSearchMode::Buffer,
            terminal_search_case_sensitive: false,
            terminal_search_regex: false,
            terminal_search_whole_word: false,
            terminal_search_active_index: 0,
            terminal_history_search_pending_key: None,
            terminal_history_search_result: None,
            search_engine_edit_index: None,
            search_engine_expanded_index: None,
            search_engine_icon_picker_index: None,
            search_engine_actions_index: None,
            search_engine_edit_field: SearchEngineEditorField::Name,
            search_engine_focus: cx.focus_handle(),
            terminal_scrollbar_dragging: false,
            terminal_scrollbar_drag_session_id: None,
            terminal_actions_open: false,
            terminal_actions_focus: cx.focus_handle(),
            terminal_context_menu: None,
            action_link_menu: None,
            action_link_tooltip: None,
            action_link_hover_pending: None,
            translation_dialog: None,
            bottom_panel: if settings.ui_serial_send_visible {
                BottomPanelMode::CommandSend
            } else if settings.ui_quick_cmd_visible {
                BottomPanelMode::QuickCommands
            } else {
                BottomPanelMode::Hidden
            },
            quick_cmd_height,
            serial_send_height,
            bottom_panel_resize: None,
            send_command_draft: String::new(),
            send_command_focus: cx.focus_handle(),
            send_command_controls_focus: cx.focus_handle(),
            send_command_control_focus: None,
            send_command_data_type: SendCommandDataType::Text,
            send_command_mode: SendCommandMode::Line,
            send_command_count: Some(1),
            send_command_count_input: "1".to_string(),
            send_command_interval_seconds: 1.0,
            send_command_interval_input: "1.00".to_string(),
            send_command_line_ending: SendCommandLineEnding::Crlf,
            send_command_target: SendCommandTarget::Current,
            send_command_data_menu_open: false,
            send_command_mode_menu_open: false,
            send_command_target_menu_open: false,
            send_command_line_ending_menu_open: false,
            send_command_sending: false,
            send_command_cancel: None,
            send_command_progress_completed: 0,
            send_command_progress_total: 0,
            send_command_progress_round: 0,
            send_command_progress_rounds: 0,
            sync_groups: Vec::new(),
            sync_groups_open: false,
            sync_groups_focus: cx.focus_handle(),
            sync_groups_selected_id: None,
            broadcast_to_all: false,
            keyword_highlights,
            keyword_highlight_expanded_id: None,
            keyword_highlight_edit_id: None,
            keyword_highlight_edit_field: KeywordHighlightEditorField::Name,
            keyword_highlight_focus: cx.focus_handle(),
            settings,
            settings_master_password_enabled,
            settings_master_password_draft: String::new(),
            settings_master_password_focus: cx.focus_handle(),
            interaction_word_separators_focus: cx.focus_handle(),
            terminal_x11_display_focus: cx.focus_handle(),
            appearance_menu_open: None,
            appearance_ui_font_options,
            appearance_terminal_font_options,
            keybinding_recording_id: None,
            keybinding_pending_keys: None,
            keybinding_search_draft: String::new(),
            keybinding_search_focus: cx.focus_handle(),
            keybindings_focus: cx.focus_handle(),
            store_status,
            session_manager,
            session_event_bridge,
            recording_manager,
            recording_active_count: 0,
            pending_auto_recording_session: None,
            recording_write_pipeline,
            recording_search_draft: String::new(),
            recording_search_focus: cx.focus_handle(),
            recording_busy_actions: HashMap::new(),
            session_start_tx,
            session_start_rx,
            tunnel_manager: Arc::new(SshTunnelManager::new()),
            tunnel_tx,
            tunnel_rx,
            pending_tunnels: Vec::new(),
            process_tx,
            process_rx,
            processes: Vec::new(),
            process_status: "ready".to_string(),
            process_pending: false,
            process_last_refresh_at: None,
            process_search_draft: String::new(),
            process_search_focus: cx.focus_handle(),
            process_sort_key: RemoteProcessSortKey::Cpu,
            process_sort_direction: RemoteProcessSortDirection::Descending,
            process_list_offset: 0,
            docker_list_offset: 0,
            docker_resource_list_offset: 0,
            send_command_hex_scroll_x: 0.,
            send_command_hex_scroll_y: 0.,
            process_selected_pid: None,
            process_menu_pid: None,
            process_nice_draft: "0".to_string(),
            process_nice_focus: cx.focus_handle(),
            process_signal_confirm: None,
            stats_tx,
            stats_rx,
            remote_stats: None,
            stats_status: "start an SSH session to inspect remote stats".to_string(),
            stats_pending: false,
            stats_last_refresh_at: None,
            stats_cpu_expanded: false,
            translate_tx,
            translate_rx,
            translate_provider: "google".to_string(),
            translation_settings,
            translation_secret_draft: TranslationSecretDraft::default(),
            translate_target_language,
            translate_input: String::new(),
            translate_result: None,
            translate_status: "Google translation ready".to_string(),
            translate_pending: false,
            translate_focus: cx.focus_handle(),
            translate_focused_field: TranslateInputField::Text,
            update_tx,
            update_rx,
            update_status: format!("Current version {}", env!("CARGO_PKG_VERSION")),
            update_info: None,
            update_pending: false,
            about_open: false,
            docker_tx,
            docker_rx,
            docker_overview: None,
            docker_status: "start an SSH session to inspect Docker".to_string(),
            docker_pending: false,
            docker_last_refresh_at: None,
            docker_details: None,
            docker_details_container_id: None,
            docker_details_last_refresh_at: None,
            docker_confirm: None,
            docker_container_menu_id: None,
            docker_compose_menu_id: None,
            docker_tab: DockerTab::Containers,
            docker_search_draft: String::new(),
            docker_search_focus: cx.focus_handle(),
            docker_compose_expanded: HashSet::new(),
            docker_compose_services: HashMap::new(),
            docker_compose_service_errors: HashMap::new(),
            transfer_tx,
            transfer_rx,
            transfer_jobs: Vec::new(),
            transfer_selected_job_id: None,
            transfer_job_delete: None,
            transfer_job_menu: None,
            transfer_remote_path: ".".to_string(),
            transfer_local_path: "nyaterm-download.bin".to_string(),
            transfer_duplicate_policy,
            transfer_path_prompt: None,
            transfer_browser_path: ".".to_string(),
            transfer_browser_home_dir: String::new(),
            transfer_browser_home_dir_pending: false,
            transfer_browser_path_draft: String::new(),
            transfer_browser_path_editing: false,
            transfer_browser_entries: Vec::new(),
            transfer_browser_status: "List a remote directory to browse files.".to_string(),
            transfer_browser_search: String::new(),
            transfer_browser_list_offset: 0,
            transfer_browser_search_expanded: false,
            transfer_browser_history: VecDeque::new(),
            transfer_browser_history_index: 0,
            transfer_browser_visited_history: VecDeque::new(),
            transfer_browser_session_cache: HashMap::new(),
            transfer_auto_sync_cwd_last_at: None,
            transfer_browser_favorites: VecDeque::new(),
            transfer_browser_sort_column: TransferBrowserSortColumn::Name,
            transfer_browser_sort_direction: TransferBrowserSortDirection::Ascending,
            transfer_browser_column_widths: TransferBrowserColumnWidths::default(),
            transfer_browser_column_resize: None,
            transfer_selected_remote_path: None,
            transfer_selected_remote_paths: HashSet::new(),
            transfer_browser_drag_selection: None,
            transfer_browser_pending_rename: None,
            transfer_browser_pending_rename_token: 0,
            transfer_browser_context_menu: None,
            transfer_browser_favorites_menu: None,
            transfer_browser_upload_menu: None,
            transfer_rename: None,
            transfer_rename_focus_pending: false,
            transfer_move: None,
            transfer_delete: None,
            transfer_new_folder: None,
            transfer_new_file: None,
            transfer_new_symlink: None,
            transfer_properties: None,
            transfer_editor: None,
            remote_editor_window: None,
            transfer_unknown_file: None,
            transfer_external_sync_prompts: HashMap::new(),
            transfer_external_sync_windows: HashMap::new(),
            transfer_external_always_uploads: HashSet::new(),
            recording_path_prompt: None,
            config_path_prompt: None,
            diagnostics_path_prompt: None,
            keyword_highlight_path_prompt: None,
            active_snapshot_password_prompt: None,
            cloud_sync_settings,
            cloud_sync_state,
            cloud_sync_history,
            cloud_sync_history_expanded: HashSet::new(),
            cloud_sync_conflict: None,
            cloud_sync_secret_draft: CloudSyncSecretDraft::default(),
            cloud_sync_status: "local provider ready".to_string(),
            cloud_sync_focus: cx.focus_handle(),
            cloud_sync_focused_field: CloudSyncInputField::RemoteRoot,
            ai_settings,
            ai_model_draft,
            ai_base_url_draft,
            ai_secret_draft: String::new(),
            ai_status: "AI settings ready".to_string(),
            ai_session_count,
            ai_message_count,
            ai_audit_count,
            ai_discovery_tx,
            ai_discovery_rx,
            ai_discovery_pending: false,
            ai_chat_tx,
            ai_chat_rx,
            ai_chat_pending: false,
            ai_chat_job_id: 0,
            ai_chat_cancel: None,
            ai_chat_session_id: format!("ai-session-{}", uuid()),
            ai_prompt_draft: String::new(),
            ai_target_session_ids: Vec::new(),
            ai_mention_open: false,
            ai_mention_query: String::new(),
            ai_mention_index: 0,
            ai_prepared_request: None,
            ai_response_preview: "Ask mode ready".to_string(),
            ai_chat_messages: Vec::new(),
            ai_streaming_assistant_id: None,
            ai_history_open: false,
            ai_history_query: String::new(),
            ai_history_search_focus: cx.focus_handle(),
            ai_clear_history_confirm_open: false,
            ai_clear_history_confirm_focus: cx.focus_handle(),
            ai_auto_execution_confirm_open: false,
            ai_auto_execution_confirm_focus: cx.focus_handle(),
            ai_sessions: Vec::new(),
            ai_message_menu: None,
            ai_quoted_text: None,
            ai_detected_error: None,
            ai_error_notice_at: HashMap::new(),
            ai_model_menu_open: false,
            ai_model_query: String::new(),
            ai_model_index: 0,
            ai_model_search_focus: cx.focus_handle(),
            ai_command_cards: Vec::new(),
            ai_agent_task_prompt: None,
            ai_agent_step_index: 0,
            ai_agent_loop: None,
            ai_agent_capture: AgentOutputCaptureProcessor::new(),
            ai_agent_steps: Vec::new(),
            ai_agent_thought_expanded: HashSet::new(),
            ai_agent_output_expanded: HashSet::new(),
            ai_chat_focus: cx.focus_handle(),
            ai_chat_focus_pending: false,
            ai_focus: cx.focus_handle(),
            ai_focused_field: AiInputField::Model,
            ai_action_expanded: None,
            ai_action_edit: None,
            ai_action_focus: cx.focus_handle(),
            ai_model_collapsed_groups: HashSet::new(),
            ai_manual_model_drafts: HashMap::new(),
            ai_manual_model_focus: cx.focus_handle(),
            ai_manual_model_edit_group: None,
            ai_credential_expanded_id: None,
            ai_credential_edit: None,
            ai_credential_focus: cx.focus_handle(),
            ai_credential_secret_drafts: HashMap::new(),
            transfer_focus: cx.focus_handle(),
            transfer_queue_focus: cx.focus_handle(),
            transfer_browser_focus: cx.focus_handle(),
            transfer_browser_path_focus: cx.focus_handle(),
            transfer_browser_search_focus: cx.focus_handle(),
            transfer_rename_focus: cx.focus_handle(),
            transfer_move_focus: cx.focus_handle(),
            transfer_delete_focus: cx.focus_handle(),
            transfer_new_folder_focus: cx.focus_handle(),
            transfer_new_file_focus: cx.focus_handle(),
            transfer_new_symlink_focus: cx.focus_handle(),
            transfer_properties_focus: cx.focus_handle(),
            transfer_editor_focus: cx.focus_handle(),
            transfer_unknown_file_focus: cx.focus_handle(),
            transfer_external_sync_focus: cx.focus_handle(),
            transfer_job_delete_focus: cx.focus_handle(),
            transfer_default_editor_focus: cx.focus_handle(),
            transfer_download_path_focus: cx.focus_handle(),
            recording_path_focus: cx.focus_handle(),
            transfer_focused_field: TransferInputField::Remote,
            duplicate_prompts: Arc::new(SftpDuplicatePromptBroker::default()),
            active_duplicate_prompt: None,
            pending_session_starts: HashMap::new(),
            session_pane_states: HashMap::new(),
            pending_reconnect_replace_id: None,
            pending_workspace_split: None,
            host_key_prompts: Arc::new(HostKeyPromptBroker::default()),
            active_host_key_prompt: None,
            credential_prompts: Arc::new(CredentialPromptBroker::default()),
            active_credential_prompt: None,
            credential_prompt_focus_pending: false,
            credential_focus: cx.focus_handle(),
            snapshot_password_focus: cx.focus_handle(),
            otp_provider,
            active_session_id: None,
            active_ssh_config: None,
            active_ai_execution_profile: AiExecutionProfile::SendOnly,
            session_order: Vec::new(),
            session_metadata: HashMap::new(),
            session_custom_names: HashMap::new(),
            session_dynamic_titles: HashMap::new(),
            session_cwds: HashMap::new(),
            zmodem_sessions: HashMap::new(),
            trzsz_sessions: HashMap::new(),
            session_tab_colors: HashMap::new(),
            ssh_multiplex_handles: HashMap::new(),
            terminal_views: HashMap::new(),
            terminal_surfaces: HashMap::new(),
            tab_actions_session_id: None,
            tab_actions_anchor: None,
            tab_actions_focus: cx.focus_handle(),
            close_all_sessions_confirm_open: false,
            pending_quit_after_close_all: false,
            pending_window_quit: false,
            close_all_sessions_confirm_focus: cx.focus_handle(),
            rename_session_id: None,
            rename_draft: String::new(),
            rename_focus: cx.focus_handle(),
            color_picker_open: false,
            color_picker_focus: cx.focus_handle(),
            session_info_open: false,
            session_info_focus: cx.focus_handle(),
            startup_command_open: false,
            startup_command_action: StartupCommandAction::Duplicate,
            startup_command_draft: String::new(),
            startup_command_delay_ms: DEFAULT_DUPLICATE_STARTUP_DELAY_MS,
            startup_command_focus: cx.focus_handle(),
            temporary_ssh_link_open: false,
            temporary_ssh_link_draft: String::new(),
            temporary_ssh_link_error: None,
            temporary_ssh_link_focus: cx.focus_handle(),
            multi_line_paste: None,
            multi_line_paste_focus: cx.focus_handle(),
            terminal_focus: cx.focus_handle(),
            terminal_focus_active: false,
            terminal_focus_subscriptions: Vec::new(),
            terminal_ime_marked_text: String::new(),
            lock_focus: cx.focus_handle(),
            lock_password_draft: String::new(),
            lock_status: String::new(),
            terminal_output: String::from(INITIAL_TERMINAL_BANNER),
            terminal_output_decoder,
            terminal_screen,
            terminal_frame_pipeline,
            terminal_scroll_offset: 0,
            terminal_scroll_delta_residuals: HashMap::new(),
            terminal_status: "idle".to_string(),
            terminal_runtime: TerminalRuntimeUiState::default(),
            pending_terminal_frame_events: VecDeque::new(),
            pending_session_events: VecDeque::new(),
            diagnostic_log_last_at: HashMap::new(),
            terminal_selection: None,
            terminal_selection_dragging: false,
            terminal_mouse_report_button: None,
            terminal_mouse_report_session_id: None,
            terminal_mouse_report_peer_session_ids: Vec::new(),
            terminal_mouse_report_position: None,
            terminal_surface_bounds: None,
            terminal_session_surface_bounds: HashMap::new(),
            terminal_cell_metrics: None,
            cached_terminal_theme_palette: None,
            cached_keyword_highlight_rules: None,
            terminal_file_drop_hover: None,
            last_viewport_size: (1280., 800.),
            wallpaper_tile_dimensions: None,
            last_viewport_change_at: None,
            title_drag_active_until: None,
            selected_nav: NavItem::Workspace,
            main_mode: MainMode::Workspace,
            settings_active_tab: SettingsTab::General,
            settings_expanded_groups: HashSet::from(["workspace".to_string()]),
            settings_draft_snapshot: None,
            settings_window: None,
            settings_previous_left_collapsed: None,
            settings_previous_right_collapsed: None,
            active_left_panel,
            active_right_panel,
            left_open_panels,
            right_open_panels,
            panel_stack_sizes,
            panel_multi_open,
            right_focus: RightFocus::Default,
            left_sidebar_collapsed,
            right_inspector_collapsed,
            mobile_left_open: false,
            mobile_right_open: false,
            left_panel_width,
            right_panel_width,
            transfer_panel_height,
            panel_resize: None,
            transfer_height_resize: None,
            panel_stack_resize: None,
            activity_bar_layout,
            activity_bar_context_menu: None,
            title_menu_open: None,
            title_menu_submenu: None,
            open_tabs_menu_open: false,
            new_session_menu_open: false,
            new_session_all_sessions_open: false,
            new_session_group_menu_path: Vec::new(),
            session_tab_strip_scroll: ScrollHandle::new(),
            session_tab_scroll_into_view_pending: false,
            last_connect_failure_name: None,
            last_connect_failure_error: None,
            security_auth_tab: SecurityAuthTab::Keys,
            security_key_editor: None,
            security_key_editor_focus: cx.focus_handle(),
            security_otp_editor: None,
            security_otp_editor_focus: cx.focus_handle(),
            security_password_editor: None,
            security_password_editor_focus: cx.focus_handle(),
            security_credential_editor: None,
            security_credential_editor_focus: cx.focus_handle(),
            security_delete_confirm: None,
            security_otp_codes: HashMap::new(),
            security_revealed_passwords: HashMap::new(),
            security_revealed_credentials: HashMap::new(),
            security_status: "security ready".to_string(),
            security_secrets_unlocked,
            security_unlock_prompt_open: false,
            security_unlock_draft: String::new(),
            security_unlock_error: None,
            security_unlock_focus: cx.focus_handle(),
            workspace_split: None,
            workspace_split_resize: None,
            session_pane_roots: HashMap::new(),
            session_tab_owner: HashMap::new(),
            terminal_windows: None,
            focused_terminal_window_leaf_id: None,
            terminal_window_drop: None,
            terminal_windows_restored: false,
            workspace_pane_layout_restored: false,
            startup_restore_complete: false,
            is_locked: false,
            last_user_activity_at: Instant::now(),
        }
    }
}
