use super::*;

use crate::models::{
    ActionLinkMenuState, ActionLinkTooltipState, ActiveSessionMenuState,
    ActivityBarContextMenuState, ActivityBarLayoutState, AiActionEditorField, AiActionListKind,
    AiCredentialEditorField, AiDetectedErrorState, AiInputField, AiMessageMenuState,
    AiPreparedRequest, BottomPanelMode, BottomPanelResizeState, CloudSyncConflictState,
    CloudSyncSecretDraft, CommandSuggestionState, ConfigPathPromptKind, CredentialSuggestionState,
    DiagnosticsPathPromptKind, DockerConfirmState, DockerTab, GithubGistAuthJobEvent,
    GithubGistAuthState, KeywordHighlightEditorField, KeywordHighlightPathPromptKind, MainMode,
    MultiLinePasteDraft, PanelResizeState, PanelStackResizeState, PendingCredentialAutofill,
    RecordingHistorySearchEvent, RecordingHistorySearchKey, RecordingPathPromptKind,
    RecordingWritePipeline, RemoteProcessSignalConfirmState, RemoteProcessSortDirection,
    RemoteProcessSortKey, RightFocus, SearchEngineEditorField, SecurityAuthTab,
    SecurityCredentialEditorState, SecurityDeleteConfirmState, SecurityKeyEditorState,
    SecurityOtpEditorState, SecurityPasswordEditorState, SecurityUnlockAction, SessionEventBridge,
    SessionRuntimeMetadata, SettingsTab, SnapshotPasswordPromptState, StartupCommandAction,
    StartupCommandRequest, StoreStatus, SyncInputGroup, TabActionsSubmenu, TabDockZone,
    TerminalContextMenuState, TerminalFrameEvent, TerminalFramePipeline, TerminalSearchMode,
    TerminalSelection, TerminalWindowNode, TitleMenu, TitleMenuSubmenu,
    TransferBrowserColumnResizeState, TransferBrowserColumnWidths, TransferBrowserContextMenuState,
    TransferBrowserDragSelectionState, TransferBrowserFavoritesMenuState,
    TransferBrowserPendingRenameState, TransferBrowserSessionCacheState, TransferBrowserSortColumn,
    TransferBrowserSortDirection, TransferBrowserUploadMenuState, TransferDeleteState,
    TransferEditorWorkspaceState, TransferExternalSyncPromptState, TransferHeightResizeState,
    TransferInputField, TransferJobDeleteState, TransferJobMenuState, TransferMoveState,
    TransferNewFileState, TransferNewFolderState, TransferNewSymlinkState, TransferPathPromptKind,
    TransferPropertiesState, TransferRenameState, TransferUnknownFileState, TranslateInputField,
    TranslationDialogState, TranslationSecretDraft, WorkspacePaneNode, WorkspaceSplitDirection,
    WorkspaceSplitResizeState, WorkspaceSplitState,
};
use nyaterm_core::{AiSession, TranslateResult, TranslationSettings};

use crate::send_command::{
    SendCommandControlFocus, SendCommandDataType, SendCommandLineEnding, SendCommandMode,
    SendCommandTarget,
};

mod construct;
mod types;

pub(in crate::features) use types::{
    FailedSessionStart, PendingSavedConnectionStart, PendingSessionStart,
    SavedConnectionStartOptions, SessionPaneState, SettingsDraftSnapshot, TerminalRuntimeUiState,
};

pub struct NyaTermApp {
    pub(in crate::features) stores: crate::entities::UiStoreHandles,
    pub(in crate::features) runtime: AppRuntime,
    pub(in crate::features) services: NativeServices,
    pub(in crate::features) inventory: MigrationInventory,
    pub(in crate::features) connections: Vec<SavedConnection>,
    pub(in crate::features) pending_saved_connection_queue: VecDeque<PendingSavedConnectionStart>,
    pub(in crate::features) connection_groups: Vec<Group>,
    pub(in crate::features) connection_state: ConnectionFeatureState,
    pub(in crate::features) ai_execution_menu_open: bool,
    pub(in crate::features) connection_ssh_keys: Vec<SshKey>,
    pub(in crate::features) connection_otp_entries: Vec<OtpEntry>,
    pub(in crate::features) connection_saved_passwords: Vec<SavedPassword>,
    pub(in crate::features) connection_saved_credentials: Vec<SavedCredential>,
    pub(in crate::features) connection_serial_ports: Vec<String>,
    pub(in crate::features) tunnels: Vec<TunnelConfig>,
    pub(in crate::features) tunnel_groups: Vec<TunnelGroup>,
    pub(in crate::features) proxies: Vec<ProxyConfig>,
    pub(in crate::features) proxy_groups: Vec<ProxyGroup>,
    pub(in crate::features) quick_commands: Arc<[QuickCommand]>,
    pub(in crate::features) quick_command_categories: Vec<QuickCommandCategory>,
    pub(in crate::features) quick_command_state: QuickCommandFeatureState,
    pub(in crate::features) command_history: Arc<[CommandHistoryEntry]>,
    pub(in crate::features) command_persistence_tx: mpsc::Sender<CommandPersistenceRequest>,
    pub(in crate::features) command_persistence_rx: mpsc::Receiver<CommandPersistenceResult>,
    pub(in crate::features) command_persistence_pending: usize,
    pub(in crate::features) session_command_history: HashMap<String, Vec<String>>,
    pub(in crate::features) command_search_draft: String,
    /// Inline terminal command suggestions (Tauri CommandSuggestions).
    pub(in crate::features) command_suggestions: Option<CommandSuggestionState>,
    /// Local terminal input tracker for inline suggestions (Tauri terminalInputTracker).
    pub(in crate::features) command_input_tracker: TerminalInputState,
    /// Hide suggestions after interactive programs (vim/htop/less/...) until Ctrl+C/q.
    pub(in crate::features) command_suggestions_suppressed: bool,
    /// Command captured from tracker at Enter, consumed by history recording.
    pub(in crate::features) pending_command_history_entry: Option<String>,
    /// Bumps to cancel in-flight 80ms suggestion search timers (Tauri searchTimer).
    pub(in crate::features) command_suggestion_search_gen: u64,
    /// Owning the debounce task lets a newer key cancel the previous timer.
    pub(in crate::features) command_suggestion_refresh_task: Option<gpui::Task<()>>,
    /// Terminal-output credential autofill panel (Tauri CredentialSuggestions).
    pub(in crate::features) credential_suggestions: Option<CredentialSuggestionState>,
    pub(in crate::features) credential_autofill_buffer: String,
    pub(in crate::features) credential_autofill_recent: HashMap<String, u64>,
    pub(in crate::features) credential_autofill_pending: Option<PendingCredentialAutofill>,
    pub(in crate::features) credential_autofill_detection_pending: bool,
    pub(in crate::features) credential_autofill_next_request_id: u64,
    pub(in crate::features) credential_autofill_pending_request:
        Option<CredentialAutofillMatchRequestKey>,
    pub(in crate::features) credential_autofill_match_pipeline: CredentialAutofillMatchPipeline,
    pub(in crate::features) credential_autofill_sending: bool,
    /// Suppress command suggestions while a password/username prompt is active.
    pub(in crate::features) credential_prompt_input_until_ms: u64,

    pub(in crate::features) command_search_focus: FocusHandle,
    pub(in crate::features) active_sessions_search_draft: String,
    pub(in crate::features) active_sessions_search_focus: FocusHandle,
    /// Root-level reconnect/disconnect overflow menu (Tauri ActiveSessions DropdownMenu).
    pub(in crate::features) active_session_menu: Option<ActiveSessionMenuState>,
    /// Per-session reconnect/disconnect busy state ("reconnect" | "disconnect").
    pub(in crate::features) active_session_busy_actions: HashMap<String, String>,
    pub(in crate::features) quick_switch_focus: FocusHandle,
    pub(in crate::features) terminal_search_open: bool,
    pub(in crate::features) terminal_search_query: String,
    pub(in crate::features) terminal_search_focus: FocusHandle,
    pub(in crate::features) terminal_search_mode: TerminalSearchMode,
    pub(in crate::features) terminal_search_case_sensitive: bool,
    pub(in crate::features) terminal_search_regex: bool,
    pub(in crate::features) terminal_search_whole_word: bool,
    pub(in crate::features) terminal_search_active_index: usize,
    pub(in crate::features) terminal_history_search_pending_key: Option<RecordingHistorySearchKey>,
    pub(in crate::features) terminal_history_search_result: Option<RecordingHistorySearchEvent>,
    /// Which search engine row is focused for name/url editing (Settings → Search).
    pub(in crate::features) search_engine_edit_index: Option<usize>,
    pub(in crate::features) search_engine_expanded_index: Option<usize>,
    pub(in crate::features) search_engine_icon_picker_index: Option<usize>,
    pub(in crate::features) search_engine_actions_index: Option<usize>,
    pub(in crate::features) search_engine_edit_field: SearchEngineEditorField,
    pub(in crate::features) search_engine_focus: FocusHandle,
    /// Dragging the terminal scrollback scrollbar thumb.
    pub(in crate::features) terminal_scrollbar_dragging: bool,
    pub(in crate::features) terminal_scrollbar_drag_session_id: Option<String>,
    pub(in crate::features) terminal_actions_open: bool,
    pub(in crate::features) terminal_actions_focus: FocusHandle,
    pub(in crate::features) terminal_context_menu: Option<TerminalContextMenuState>,
    pub(in crate::features) action_link_menu: Option<ActionLinkMenuState>,
    pub(in crate::features) action_link_tooltip: Option<ActionLinkTooltipState>,
    /// Pending action-link hover (Tauri 250ms delay before showing tooltip).
    pub(in crate::features) action_link_hover_pending:
        Option<(String, Instant, ActionLinkTooltipState)>,

    pub(in crate::features) translation_dialog: Option<TranslationDialogState>,
    pub(in crate::features) bottom_panel: BottomPanelMode,
    pub(in crate::features) quick_cmd_height: f32,
    pub(in crate::features) serial_send_height: f32,
    pub(in crate::features) bottom_panel_resize: Option<BottomPanelResizeState>,
    pub(in crate::features) send_command_draft: String,
    pub(in crate::features) send_command_focus: FocusHandle,
    pub(in crate::features) send_command_controls_focus: FocusHandle,
    pub(in crate::features) send_command_control_focus: Option<SendCommandControlFocus>,
    pub(in crate::features) send_command_data_type: SendCommandDataType,
    pub(in crate::features) send_command_mode: SendCommandMode,
    pub(in crate::features) send_command_count: Option<u32>,
    pub(in crate::features) send_command_count_input: String,
    pub(in crate::features) send_command_interval_seconds: f64,
    pub(in crate::features) send_command_interval_input: String,
    pub(in crate::features) send_command_line_ending: SendCommandLineEnding,
    pub(in crate::features) send_command_target: SendCommandTarget,
    pub(in crate::features) send_command_data_menu_open: bool,
    pub(in crate::features) send_command_mode_menu_open: bool,
    pub(in crate::features) send_command_target_menu_open: bool,
    pub(in crate::features) send_command_line_ending_menu_open: bool,
    pub(in crate::features) send_command_sending: bool,
    pub(in crate::features) send_command_cancel: Option<Arc<AtomicBool>>,
    pub(in crate::features) send_command_progress_completed: u32,
    pub(in crate::features) send_command_progress_total: u32,
    pub(in crate::features) send_command_progress_round: u32,
    pub(in crate::features) send_command_progress_rounds: u32,
    pub(in crate::features) sync_groups: Vec<SyncInputGroup>,
    pub(in crate::features) sync_groups_open: bool,
    pub(in crate::features) sync_groups_focus: FocusHandle,
    pub(in crate::features) sync_groups_search_draft: String,
    pub(in crate::features) sync_groups_search_marked_text: String,
    pub(in crate::features) sync_groups_name_marked_text: String,
    pub(in crate::features) sync_groups_search_focus: FocusHandle,
    pub(in crate::features) sync_groups_name_focus: FocusHandle,
    pub(in crate::features) sync_groups_selected_id: Option<String>,
    pub(in crate::features) sync_groups_delete_pending: Option<String>,
    /// Broadcast keyboard input to every live session (Tauri broadcastToAll).
    pub(in crate::features) broadcast_to_all: bool,
    pub(in crate::features) keyword_highlights: KeywordHighlightConfig,
    pub(in crate::features) keyword_highlight_expanded_id: Option<String>,
    pub(in crate::features) keyword_highlight_edit_id: Option<String>,
    pub(in crate::features) keyword_highlight_edit_field: KeywordHighlightEditorField,
    pub(in crate::features) keyword_highlight_focus: FocusHandle,
    pub(in crate::features) settings: AppSettingsSummary,
    pub(in crate::features) settings_master_password_enabled: bool,
    pub(in crate::features) settings_master_password_draft: String,
    pub(in crate::features) settings_master_password_focus: FocusHandle,
    pub(in crate::features) interaction_word_separators_focus: FocusHandle,
    pub(in crate::features) terminal_x11_display_focus: FocusHandle,
    pub(in crate::features) appearance_menu_open: Option<String>,
    pub(in crate::features) appearance_ui_font_options: Vec<String>,
    pub(in crate::features) appearance_terminal_font_options: Vec<String>,
    pub(in crate::features) keybinding_recording_id: Option<String>,
    pub(in crate::features) keybinding_pending_keys: Option<String>,
    pub(in crate::features) keybinding_search_draft: String,
    pub(in crate::features) keybinding_search_focus: FocusHandle,
    pub(in crate::features) keybindings_focus: FocusHandle,
    pub(in crate::features) store_status: StoreStatus,
    pub(in crate::features) session_manager: Arc<SessionManager>,
    pub(in crate::features) session_event_bridge: SessionEventBridge,
    pub(in crate::features) recording_manager: Arc<RecordingManager>,
    /// Cached count of sessions with active file recording (paint-safe).
    pub(in crate::features) recording_active_count: usize,
    /// Deferred auto-start recording after connect (avoid file open on success arm).
    pub(in crate::features) pending_auto_recording_session: Option<(String, String)>,
    pub(in crate::features) recording_write_pipeline: RecordingWritePipeline,
    pub(in crate::features) recording_search_draft: String,
    pub(in crate::features) recording_search_focus: FocusHandle,
    /// Per-session recording panel busy state ("record" | "save").
    pub(in crate::features) recording_busy_actions: HashMap<String, String>,
    pub(in crate::features) session_start_tx: mpsc::Sender<SessionStartResult>,
    pub(in crate::features) session_start_rx: mpsc::Receiver<SessionStartResult>,
    pub(in crate::features) tunnel_manager: Arc<SshTunnelManager>,
    pub(in crate::features) tunnel_tx: mpsc::Sender<TunnelJobResult>,
    pub(in crate::features) tunnel_rx: mpsc::Receiver<TunnelJobResult>,
    pub(in crate::features) pending_tunnels: Vec<String>,
    pub(in crate::features) process_tx: mpsc::Sender<ProcessJobResult>,
    pub(in crate::features) process_rx: mpsc::Receiver<ProcessJobResult>,
    pub(in crate::features) processes: Vec<RemoteProcess>,
    pub(in crate::features) process_snapshot_loaded: bool,
    pub(in crate::features) process_status: String,
    pub(in crate::features) process_pending: bool,
    pub(in crate::features) process_job_id: u64,
    pub(in crate::features) process_job_session_id: Option<String>,
    pub(in crate::features) process_consecutive_refresh_failures: u8,
    pub(in crate::features) process_last_refresh_at: Option<Instant>,
    pub(in crate::features) process_search_draft: String,
    pub(in crate::features) process_search_focus: FocusHandle,
    pub(in crate::features) process_sort_key: RemoteProcessSortKey,
    pub(in crate::features) process_sort_direction: RemoteProcessSortDirection,
    pub(in crate::features) process_list_offset: usize,
    pub(in crate::features) docker_list_offset: usize,
    pub(in crate::features) docker_resource_list_offset: usize,
    pub(in crate::features) send_command_hex_scroll_x: f32,
    pub(in crate::features) send_command_hex_scroll_y: f32,
    pub(in crate::features) process_selected_pid: Option<u32>,
    pub(in crate::features) process_menu_pid: Option<u32>,
    pub(in crate::features) process_nice_draft: String,
    pub(in crate::features) process_nice_focus: FocusHandle,
    pub(in crate::features) process_signal_confirm: Option<RemoteProcessSignalConfirmState>,
    pub(in crate::features) stats_tx: mpsc::Sender<StatsJobResult>,
    pub(in crate::features) stats_rx: mpsc::Receiver<StatsJobResult>,
    pub(in crate::features) remote_stats: Option<RemoteStats>,
    pub(in crate::features) stats_status: String,
    pub(in crate::features) stats_pending: bool,
    pub(in crate::features) stats_job_id: u64,
    pub(in crate::features) stats_job_session_id: Option<String>,
    pub(in crate::features) stats_consecutive_refresh_failures: u8,
    pub(in crate::features) stats_last_refresh_at: Option<Instant>,
    pub(in crate::features) stats_cpu_expanded: bool,
    pub(in crate::features) translate_tx: mpsc::Sender<TranslateJobResult>,
    pub(in crate::features) translate_rx: mpsc::Receiver<TranslateJobResult>,
    pub(in crate::features) translate_provider: String,
    pub(in crate::features) translation_settings: TranslationSettings,
    pub(in crate::features) translation_secret_draft: TranslationSecretDraft,
    pub(in crate::features) translate_target_language: String,
    pub(in crate::features) translate_input: String,
    pub(in crate::features) translate_result: Option<TranslateResult>,
    pub(in crate::features) translate_status: String,
    pub(in crate::features) translate_pending: bool,
    pub(in crate::features) translate_focus: FocusHandle,
    pub(in crate::features) translate_focused_field: TranslateInputField,
    pub(in crate::features) update_tx: mpsc::Sender<UpdateJobResult>,
    pub(in crate::features) update_rx: mpsc::Receiver<UpdateJobResult>,
    pub(in crate::features) update_status: String,
    pub(in crate::features) update_info: Option<NativeUpdateInfo>,
    pub(in crate::features) update_pending: bool,
    pub(in crate::features) update_dialog_open: bool,
    pub(in crate::features) about_open: bool,
    pub(in crate::features) docker_tx: mpsc::Sender<DockerJobResult>,
    pub(in crate::features) docker_rx: mpsc::Receiver<DockerJobResult>,
    pub(in crate::features) docker_overview: Option<RemoteDockerOverview>,
    pub(in crate::features) docker_status: String,
    pub(in crate::features) docker_pending: bool,
    pub(in crate::features) docker_job_id: u64,
    pub(in crate::features) docker_job_session_id: Option<String>,
    pub(in crate::features) docker_consecutive_refresh_failures: u8,
    pub(in crate::features) docker_last_refresh_at: Option<Instant>,
    pub(in crate::features) docker_details: Option<DockerContainerDetails>,
    pub(in crate::features) docker_details_container_id: Option<String>,
    pub(in crate::features) docker_details_last_refresh_at: Option<Instant>,
    pub(in crate::features) docker_confirm: Option<DockerConfirmState>,
    pub(in crate::features) docker_container_menu_id: Option<String>,
    pub(in crate::features) docker_compose_menu_id: Option<String>,
    pub(in crate::features) docker_tab: DockerTab,
    pub(in crate::features) docker_tab_menu_open: bool,
    pub(in crate::features) docker_header_menu_open: bool,
    pub(in crate::features) docker_search_draft: String,
    pub(in crate::features) docker_search_focus: FocusHandle,
    pub(in crate::features) docker_compose_expanded: HashSet<String>,
    pub(in crate::features) docker_compose_services: HashMap<String, Vec<DockerComposeService>>,
    pub(in crate::features) docker_compose_service_errors: HashMap<String, String>,
    pub(in crate::features) transfer_tx: mpsc::Sender<TransferJobResult>,
    pub(in crate::features) transfer_rx: mpsc::Receiver<TransferJobResult>,
    pub(in crate::features) transfer_jobs: Vec<TransferJobState>,
    pub(in crate::features) transfer_selected_job_id: Option<String>,
    pub(in crate::features) transfer_job_delete: Option<TransferJobDeleteState>,
    pub(in crate::features) transfer_job_menu: Option<TransferJobMenuState>,
    pub(in crate::features) transfer_remote_path: String,
    pub(in crate::features) transfer_local_path: String,
    pub(in crate::features) transfer_duplicate_policy: SftpDuplicatePolicy,
    pub(in crate::features) transfer_path_prompt: Option<TransferPathPromptKind>,
    pub(in crate::features) transfer_browser_path: String,
    pub(in crate::features) transfer_browser_home_dir: String,
    pub(in crate::features) transfer_browser_home_dir_pending: bool,
    pub(in crate::features) transfer_browser_path_draft: String,
    pub(in crate::features) transfer_browser_path_editing: bool,
    pub(in crate::features) transfer_browser_entries: Vec<SftpFileEntry>,
    pub(in crate::features) transfer_browser_loading: bool,
    pub(in crate::features) transfer_browser_error: Option<String>,
    pub(in crate::features) transfer_browser_status: String,
    pub(in crate::features) transfer_browser_search: String,
    pub(in crate::features) transfer_browser_list_offset: usize,
    pub(in crate::features) transfer_browser_viewport_height: f32,
    pub(in crate::features) transfer_browser_search_expanded: bool,
    pub(in crate::features) transfer_browser_history: VecDeque<String>,
    pub(in crate::features) transfer_browser_history_index: usize,
    pub(in crate::features) transfer_browser_visited_history: VecDeque<String>,
    pub(in crate::features) transfer_browser_session_cache:
        HashMap<String, TransferBrowserSessionCacheState>,
    /// Latest SFTP navigation job per session; older results must not rewind the browser.
    pub(in crate::features) transfer_browser_navigation_jobs: HashMap<String, String>,
    pub(in crate::features) transfer_auto_sync_cwd_last_at: Option<Instant>,
    pub(in crate::features) transfer_browser_favorites: VecDeque<String>,
    pub(in crate::features) transfer_browser_sort_column: TransferBrowserSortColumn,
    pub(in crate::features) transfer_browser_sort_direction: TransferBrowserSortDirection,
    pub(in crate::features) transfer_browser_column_widths: TransferBrowserColumnWidths,
    pub(in crate::features) transfer_browser_column_resize:
        Option<TransferBrowserColumnResizeState>,
    pub(in crate::features) transfer_selected_remote_path: Option<String>,
    pub(in crate::features) transfer_selected_remote_paths: HashSet<String>,
    pub(in crate::features) transfer_browser_drag_selection:
        Option<TransferBrowserDragSelectionState>,
    pub(in crate::features) transfer_browser_pending_rename:
        Option<TransferBrowserPendingRenameState>,
    pub(in crate::features) transfer_browser_pending_rename_token: u64,
    pub(in crate::features) transfer_browser_context_menu: Option<TransferBrowserContextMenuState>,
    pub(in crate::features) transfer_browser_favorites_menu:
        Option<TransferBrowserFavoritesMenuState>,
    pub(in crate::features) transfer_browser_upload_menu: Option<TransferBrowserUploadMenuState>,
    pub(in crate::features) transfer_rename: Option<TransferRenameState>,
    pub(in crate::features) transfer_rename_focus_pending: bool,
    pub(in crate::features) transfer_move: Option<TransferMoveState>,
    pub(in crate::features) transfer_delete: Option<TransferDeleteState>,
    pub(in crate::features) transfer_new_folder: Option<TransferNewFolderState>,
    pub(in crate::features) transfer_new_file: Option<TransferNewFileState>,
    pub(in crate::features) transfer_new_symlink: Option<TransferNewSymlinkState>,
    pub(in crate::features) transfer_properties: Option<TransferPropertiesState>,
    pub(in crate::features) transfer_editor: Option<TransferEditorWorkspaceState>,
    pub(in crate::features) transfer_editor_tabs_menu_open: bool,
    pub(in crate::features) remote_editor_window: Option<WindowHandle<RemoteFileEditorWindow>>,
    pub(in crate::features) remote_editor_window_open_pending: bool,
    pub(in crate::features) transfer_unknown_file: Option<TransferUnknownFileState>,
    pub(in crate::features) transfer_external_sync_prompts:
        HashMap<String, TransferExternalSyncPromptState>,
    pub(in crate::features) transfer_external_sync_windows:
        HashMap<String, WindowHandle<TransferExternalSyncWindow>>,
    pub(in crate::features) transfer_external_sync_window_open_pending: HashSet<String>,
    pub(in crate::features) transfer_external_always_uploads: HashSet<String>,
    pub(in crate::features) recording_path_prompt: Option<RecordingPathPromptKind>,
    pub(in crate::features) config_path_prompt: Option<ConfigPathPromptKind>,
    pub(in crate::features) diagnostics_path_prompt: Option<DiagnosticsPathPromptKind>,
    pub(in crate::features) keyword_highlight_path_prompt: Option<KeywordHighlightPathPromptKind>,
    pub(in crate::features) active_snapshot_password_prompt: Option<SnapshotPasswordPromptState>,
    pub(in crate::features) cloud_sync_settings: CloudSyncSettings,
    pub(in crate::features) cloud_sync_state: CloudSyncState,
    pub(in crate::features) cloud_sync_history: Vec<CloudSyncHistoryEntry>,
    pub(in crate::features) cloud_sync_history_expanded: HashSet<String>,
    pub(in crate::features) cloud_sync_conflict: Option<CloudSyncConflictState>,
    pub(in crate::features) cloud_sync_secret_draft: CloudSyncSecretDraft,
    pub(in crate::features) cloud_sync_status: String,
    /// Prevent overlapping network jobs from applying cloud state out of order.
    pub(in crate::features) cloud_sync_job_running: bool,
    pub(in crate::features) cloud_sync_focus: FocusHandle,
    pub(in crate::features) cloud_sync_focused_field: CloudSyncInputField,
    pub(in crate::features) cloud_sync_provider_menu_open: bool,
    pub(in crate::features) github_gist_auth: GithubGistAuthState,
    pub(in crate::features) github_gist_auth_tx: mpsc::Sender<GithubGistAuthJobEvent>,
    pub(in crate::features) github_gist_auth_rx: mpsc::Receiver<GithubGistAuthJobEvent>,
    pub(in crate::features) github_gist_auth_job_id: u64,
    pub(in crate::features) github_gist_auth_cancel: Option<Arc<AtomicBool>>,
    pub(in crate::features) ai_settings: AiSettings,
    pub(in crate::features) ai_model_draft: String,
    pub(in crate::features) ai_base_url_draft: String,
    pub(in crate::features) ai_secret_draft: String,
    pub(in crate::features) ai_status: String,
    pub(in crate::features) ai_session_count: usize,
    pub(in crate::features) ai_message_count: usize,
    pub(in crate::features) ai_audit_count: usize,
    pub(in crate::features) ai_discovery_tx: mpsc::Sender<AiDiscoveryJobResult>,
    pub(in crate::features) ai_discovery_rx: mpsc::Receiver<AiDiscoveryJobResult>,
    pub(in crate::features) ai_discovery_pending: bool,
    pub(in crate::features) ai_chat_tx: mpsc::Sender<AiChatWorkerEvent>,
    pub(in crate::features) ai_chat_rx: mpsc::Receiver<AiChatWorkerEvent>,
    pub(in crate::features) ai_chat_pending: bool,
    pub(in crate::features) ai_chat_job_id: u64,
    pub(in crate::features) ai_chat_cancel: Option<Arc<AtomicBool>>,
    pub(in crate::features) ai_chat_session_id: String,
    pub(in crate::features) ai_prompt_draft: String,
    pub(in crate::features) ai_target_session_ids: Vec<String>,
    pub(in crate::features) ai_mention_open: bool,
    pub(in crate::features) ai_mention_query: String,
    pub(in crate::features) ai_mention_index: usize,
    pub(in crate::features) ai_prepared_request: Option<AiPreparedRequest>,
    pub(in crate::features) ai_response_preview: String,
    pub(in crate::features) ai_chat_messages: Vec<AiMessage>,
    pub(in crate::features) ai_streaming_assistant_id: Option<String>,
    pub(in crate::features) ai_history_open: bool,
    pub(in crate::features) ai_history_query: String,
    pub(in crate::features) ai_history_search_focus: FocusHandle,
    /// Serializes AI history storage operations and rejects stale UI results.
    pub(in crate::features) ai_history_job_id: u64,
    pub(in crate::features) ai_history_pending: bool,
    /// Prevents an older full-history count scan from overwriting newer counts.
    pub(in crate::features) ai_usage_count_job_id: u64,
    /// Serializes background AI audit read-modify-write operations.
    pub(in crate::features) ai_audit_write_lock: Arc<Mutex<()>>,
    pub(in crate::features) ai_clear_history_confirm_open: bool,
    pub(in crate::features) ai_clear_history_confirm_focus: FocusHandle,
    pub(in crate::features) ai_auto_execution_confirm_open: bool,
    pub(in crate::features) ai_auto_execution_confirm_focus: FocusHandle,
    pub(in crate::features) ai_sessions: Vec<AiSession>,
    pub(in crate::features) ai_message_menu: Option<AiMessageMenuState>,
    pub(in crate::features) ai_quoted_text: Option<String>,
    pub(in crate::features) ai_detected_error: Option<AiDetectedErrorState>,
    pub(in crate::features) ai_error_notice_at: HashMap<String, Instant>,
    pub(in crate::features) ai_model_menu_open: bool,
    pub(in crate::features) ai_model_query: String,
    pub(in crate::features) ai_model_index: usize,
    pub(in crate::features) ai_model_search_focus: FocusHandle,
    pub(in crate::features) ai_command_cards: Vec<AiCommandCard>,
    pub(in crate::features) ai_agent_task_prompt: Option<String>,
    pub(in crate::features) ai_agent_step_index: u16,
    pub(in crate::features) ai_agent_loop: Option<AiAgentLoopState>,
    pub(in crate::features) ai_agent_capture: AgentOutputCaptureProcessor,
    pub(in crate::features) ai_agent_steps: Vec<AiAgentStepView>,
    pub(in crate::features) ai_agent_thought_expanded: HashSet<u16>,
    pub(in crate::features) ai_agent_output_expanded: HashSet<u16>,
    pub(in crate::features) ai_chat_focus: FocusHandle,
    pub(in crate::features) ai_chat_focus_pending: bool,
    pub(in crate::features) ai_focus: FocusHandle,
    pub(in crate::features) ai_focused_field: AiInputField,
    pub(in crate::features) ai_action_edit: Option<(AiActionListKind, String, AiActionEditorField)>,
    pub(in crate::features) ai_action_focus: FocusHandle,
    pub(in crate::features) ai_model_collapsed_groups: HashSet<String>,
    pub(in crate::features) ai_settings_model_query: String,
    pub(in crate::features) ai_settings_model_search_focus: FocusHandle,
    pub(in crate::features) ai_manual_model_drafts: HashMap<String, String>,
    pub(in crate::features) ai_manual_model_focus: FocusHandle,
    pub(in crate::features) ai_manual_model_edit_group: Option<String>,
    pub(in crate::features) ai_credential_edit: Option<(String, AiCredentialEditorField)>,
    pub(in crate::features) ai_credential_focus: FocusHandle,
    /// Per-credential API-key drafts; empty means keep the stored secret.
    pub(in crate::features) ai_credential_secret_drafts: HashMap<String, String>,
    pub(in crate::features) transfer_focus: FocusHandle,
    pub(in crate::features) transfer_queue_focus: FocusHandle,
    pub(in crate::features) transfer_browser_focus: FocusHandle,
    pub(in crate::features) transfer_browser_path_focus: FocusHandle,
    pub(in crate::features) transfer_browser_search_focus: FocusHandle,
    pub(in crate::features) transfer_rename_focus: FocusHandle,
    pub(in crate::features) transfer_move_focus: FocusHandle,
    pub(in crate::features) transfer_delete_focus: FocusHandle,
    pub(in crate::features) transfer_new_folder_focus: FocusHandle,
    pub(in crate::features) transfer_new_file_focus: FocusHandle,
    pub(in crate::features) transfer_new_symlink_focus: FocusHandle,
    pub(in crate::features) transfer_properties_focus: FocusHandle,
    pub(in crate::features) transfer_editor_focus: FocusHandle,
    pub(in crate::features) transfer_unknown_file_focus: FocusHandle,
    pub(in crate::features) transfer_external_sync_focus: FocusHandle,
    pub(in crate::features) transfer_job_delete_focus: FocusHandle,
    pub(in crate::features) transfer_default_editor_focus: FocusHandle,
    pub(in crate::features) transfer_download_path_focus: FocusHandle,
    pub(in crate::features) recording_path_focus: FocusHandle,
    pub(in crate::features) transfer_focused_field: TransferInputField,
    pub(in crate::features) duplicate_prompts: Arc<SftpDuplicatePromptBroker>,
    pub(in crate::features) active_duplicate_prompt: Option<SftpDuplicatePromptState>,
    pub(in crate::features) pending_session_starts: HashMap<String, PendingSessionStart>,
    pub(in crate::features) active_pending_session_start: Option<String>,
    pub(in crate::features) failed_session_starts: HashMap<String, FailedSessionStart>,
    pub(in crate::features) active_failed_session_start: Option<String>,
    /// Session starts removed from the UI while their worker may still finish.
    pub(in crate::features) cancelled_session_start_requests: HashSet<String>,
    pub(in crate::features) session_pane_states: HashMap<String, SessionPaneState>,
    /// Disconnected session id being replaced by an in-flight reconnect.
    pub(in crate::features) pending_reconnect_replace_id: Option<String>,
    /// Reconnect failures rendered in their original workspace panes.
    pub(in crate::features) reconnect_session_failures: HashMap<String, String>,
    pub(in crate::features) pending_workspace_split: Option<(WorkspaceSplitDirection, String)>,
    pub(in crate::features) host_key_prompts: Arc<HostKeyPromptBroker>,
    pub(in crate::features) active_host_key_prompt: Option<HostKeyPromptRequest>,
    pub(in crate::features) credential_prompts: Arc<CredentialPromptBroker>,
    pub(in crate::features) active_credential_prompt: Option<CredentialPromptState>,
    pub(in crate::features) active_keyboard_interactive_prompt:
        Option<KeyboardInteractivePromptState>,
    pub(in crate::features) credential_prompt_focus_pending: bool,
    pub(in crate::features) credential_focus: FocusHandle,
    pub(in crate::features) snapshot_password_focus: FocusHandle,
    pub(in crate::features) otp_provider: Arc<NativeOtpProvider>,
    pub(in crate::features) active_session_id: Option<String>,
    pub(in crate::features) active_ssh_config: Option<SshSessionConfig>,
    pub(in crate::features) active_ai_execution_profile: AiExecutionProfile,
    pub(in crate::features) session_order: Vec<String>,
    pub(in crate::features) session_metadata: HashMap<String, SessionRuntimeMetadata>,
    pub(in crate::features) session_custom_names: HashMap<String, String>,
    /// OSC 0/2 titles from the session PTY (fall back when no custom rename).
    pub(in crate::features) session_dynamic_titles: HashMap<String, String>,
    /// Latest OSC 7 working directories per session.
    pub(in crate::features) session_cwds: HashMap<String, String>,
    /// Per-session ZMODEM detector / transfer state (UI-layer interception).
    pub(in crate::features) zmodem_sessions:
        HashMap<String, crate::features::session::ZmodemSessionState>,
    /// Per-session trzsz trigger detector state (pre-parser protocol slot).
    pub(in crate::features) trzsz_sessions:
        HashMap<String, crate::features::session::TrzszSessionState>,
    pub(in crate::features) session_tab_colors: HashMap<String, u32>,
    pub(in crate::features) ssh_multiplex_handles: HashMap<String, SshMultiplexHandle>,
    pub(in crate::features) terminal_views: HashMap<String, TerminalViewState>,
    /// Per-session terminal grid entities (frame notify isolation).
    pub(in crate::features) terminal_surfaces: HashMap<String, Entity<TerminalSurface>>,
    pub(in crate::features) tab_actions_session_id: Option<String>,
    pub(in crate::features) tab_actions_anchor: Option<(f32, f32)>,
    pub(in crate::features) tab_actions_submenu: Option<TabActionsSubmenu>,
    pub(in crate::features) tab_actions_focus: FocusHandle,
    pub(in crate::features) close_all_sessions_confirm_open: bool,
    pub(in crate::features) pending_quit_after_close_all: bool,
    pub(in crate::features) pending_window_quit: bool,
    pub(in crate::features) close_all_sessions_confirm_focus: FocusHandle,
    pub(in crate::features) rename_session_id: Option<String>,
    pub(in crate::features) rename_draft: String,
    pub(in crate::features) rename_marked_text: String,
    pub(in crate::features) rename_focus: FocusHandle,
    pub(in crate::features) color_picker_open: bool,
    pub(in crate::features) color_picker_focus: FocusHandle,
    pub(in crate::features) session_info_open: bool,
    pub(in crate::features) session_info_focus: FocusHandle,
    pub(in crate::features) startup_command_open: bool,
    pub(in crate::features) startup_command_action: StartupCommandAction,
    pub(in crate::features) startup_command_draft: String,
    pub(in crate::features) startup_command_marked_text: String,
    pub(in crate::features) startup_command_delay_ms: u64,
    pub(in crate::features) startup_command_focus: FocusHandle,
    pub(in crate::features) temporary_ssh_link_open: bool,
    pub(in crate::features) temporary_ssh_link_draft: String,
    pub(in crate::features) temporary_ssh_link_error: Option<&'static str>,
    pub(in crate::features) temporary_ssh_link_marked_text: String,
    pub(in crate::features) temporary_ssh_link_focus: FocusHandle,
    pub(in crate::features) multi_line_paste: Option<MultiLinePasteDraft>,
    pub(in crate::features) multi_line_paste_marked_text: String,
    pub(in crate::features) multi_line_paste_marked_range: Option<std::ops::Range<usize>>,
    pub(in crate::features) multi_line_paste_cursor: usize,
    pub(in crate::features) multi_line_paste_anchor: Option<usize>,
    pub(in crate::features) multi_line_paste_focus: FocusHandle,
    pub(in crate::features) terminal_focus: FocusHandle,
    /// True while the terminal surface owns keyboard focus.
    pub(in crate::features) terminal_focus_active: bool,
    /// Keep focus report subscriptions alive for DECSET 1004.
    pub(in crate::features) terminal_focus_subscriptions: Vec<Subscription>,
    /// Current IME preedit text for the terminal input handler.
    pub(in crate::features) terminal_ime_marked_text: String,
    pub(in crate::features) lock_focus: FocusHandle,
    pub(in crate::features) lock_password_draft: String,
    pub(in crate::features) lock_password_marked_text: String,
    pub(in crate::features) lock_status: String,
    pub(in crate::features) terminal_output: String,
    pub(in crate::features) terminal_output_decoder: TerminalOutputDecoder,
    pub(in crate::features) terminal_screen: TerminalScreen,
    pub(in crate::features) terminal_frame_pipeline: TerminalFramePipeline,
    pub(in crate::features) terminal_live_prefetch_generation: u64,
    pub(in crate::features) terminal_live_prefetch_task: Option<gpui::Task<()>>,
    /// Scroll offset for the fallback/global terminal screen (no session view).
    pub(in crate::features) terminal_scroll_offset: usize,
    /// Fractional wheel/touchpad scroll deltas that have not yet reached one row.
    pub(in crate::features) terminal_scroll_delta_residuals: HashMap<String, f32>,
    pub(in crate::features) terminal_status: String,
    pub(in crate::features) terminal_runtime: TerminalRuntimeUiState,
    pub(in crate::features) pending_terminal_frame_events: VecDeque<TerminalFrameEvent>,
    pub(in crate::features) pending_session_events: VecDeque<SessionEvent>,
    pub(in crate::features) diagnostic_log_last_at: HashMap<&'static str, Instant>,
    /// Active visible-grid selection for the focused terminal surface.
    pub(in crate::features) terminal_selection: Option<TerminalSelection>,
    /// Session whose terminal surface owns the current text selection gesture.
    pub(in crate::features) terminal_selection_session_id: Option<String>,
    /// True while the user is dragging a left-button text selection.
    pub(in crate::features) terminal_selection_dragging: bool,
    /// X10/SGR mouse button currently captured by the remote application.
    pub(in crate::features) terminal_mouse_report_button: Option<u8>,
    /// Session that owns the current remote mouse capture.
    pub(in crate::features) terminal_mouse_report_session_id: Option<String>,
    /// Sync peers that accepted the current remote mouse capture.
    pub(in crate::features) terminal_mouse_report_peer_session_ids: Vec<String>,
    /// Last reported terminal cell for release events that land outside the grid.
    pub(in crate::features) terminal_mouse_report_position: Option<(u16, u16)>,
    /// Last painted bounds of the active terminal text area (window coords).
    pub(in crate::features) terminal_surface_bounds: Option<gpui::Bounds<gpui::Pixels>>,
    /// Last painted terminal text-area bounds per live session pane.
    pub(in crate::features) terminal_session_surface_bounds:
        HashMap<String, gpui::Bounds<gpui::Pixels>>,
    /// Device scale used when terminal viewport bounds were last painted.
    pub(in crate::features) terminal_scale_factor: f32,
    /// Measured monospaced cell size (width, height) from the terminal font when available.
    pub(in crate::features) terminal_cell_metrics: Option<(f32, f32)>,
    /// Cached terminal surface palette (theme + contrast fingerprint).
    pub(in crate::features) cached_terminal_theme_palette:
        Option<(String, String, String, crate::theme::ThemePalette)>,
    /// Cached keyword highlight rules for paint (invalidated on settings change).
    pub(in crate::features) cached_keyword_highlight_rules:
        Option<std::sync::Arc<Vec<nyaterm_core::ResolvedKeywordHighlightRule>>>,
    /// Session id currently under an external file drag (drop overlay).
    pub(in crate::features) terminal_file_drop_hover: Option<String>,

    pub(in crate::features) last_viewport_size: (f32, f32),
    /// Cached intrinsic dimensions for the current tiled wallpaper path.
    pub(in crate::features) wallpaper_tile_dimensions: Option<(String, u32, u32)>,
    /// When the window viewport last changed (resize/drag geometry).
    pub(in crate::features) last_viewport_change_at: Option<Instant>,
    /// Deadline for treating title-bar window dragging as active.
    pub(in crate::features) title_drag_active_until: Option<Instant>,
    pub(in crate::features) selected_nav: NavItem,
    pub(in crate::features) main_mode: MainMode,
    pub(in crate::features) settings_active_tab: SettingsTab,
    /// Expanded multi-item groups in the settings sidebar (Tauri keeps this local to the page).
    pub(in crate::features) settings_expanded_groups: HashSet<String>,
    /// Committed values captured when the in-window settings page opens.
    pub(in crate::features) settings_draft_snapshot: Option<SettingsDraftSnapshot>,
    pub(in crate::features) settings_window: Option<WindowHandle<SettingsWindow>>,
    pub(in crate::features) settings_window_open_pending: bool,
    /// Main workspace panel state to restore after leaving the in-window settings page.
    pub(in crate::features) settings_previous_left_collapsed: Option<bool>,
    pub(in crate::features) settings_previous_right_collapsed: Option<bool>,
    pub(in crate::features) active_left_panel: Option<NavItem>,
    pub(in crate::features) active_right_panel: Option<NavItem>,
    pub(in crate::features) left_open_panels: Vec<String>,
    pub(in crate::features) right_open_panels: Vec<String>,
    pub(in crate::features) panel_stack_sizes: HashMap<String, f32>,
    pub(in crate::features) panel_multi_open: bool,
    pub(in crate::features) right_focus: RightFocus,
    pub(in crate::features) left_sidebar_collapsed: bool,
    pub(in crate::features) right_inspector_collapsed: bool,
    pub(in crate::features) mobile_left_open: bool,
    pub(in crate::features) mobile_right_open: bool,
    pub(in crate::features) left_panel_width: f32,
    pub(in crate::features) right_panel_width: f32,
    pub(in crate::features) transfer_panel_height: f32,
    pub(in crate::features) panel_resize: Option<PanelResizeState>,
    pub(in crate::features) transfer_height_resize: Option<TransferHeightResizeState>,
    pub(in crate::features) panel_stack_resize: Option<PanelStackResizeState>,
    pub(in crate::features) activity_bar_layout: ActivityBarLayoutState,
    pub(in crate::features) activity_bar_context_menu: Option<ActivityBarContextMenuState>,
    pub(in crate::features) title_menu_open: Option<TitleMenu>,
    pub(in crate::features) title_menu_submenu: Option<TitleMenuSubmenu>,
    /// Open-tabs overflow menu (Tauri TabBar expand-more when many tabs).
    pub(in crate::features) open_tabs_menu_open: bool,
    /// New-session menu next to the tab strip + control.
    pub(in crate::features) new_session_menu_open: bool,
    /// Whether the Tauri-style "All sessions" submenu is expanded.
    pub(in crate::features) new_session_all_sessions_open: bool,
    /// Hovered group ids from the root submenu through the deepest open child menu.
    pub(in crate::features) new_session_group_menu_path: Vec<String>,
    /// Horizontal scroll handle for the global session tab strip (scroll-into-view).
    pub(in crate::features) session_tab_strip_scroll: ScrollHandle,
    /// Request scroll-into-view of the active tab on next paint (Tauri TabBar).
    pub(in crate::features) session_tab_scroll_into_view_pending: bool,
    /// Last failed connect name (shown as ephemeral failed tab chrome).
    pub(in crate::features) last_connect_failure_name: Option<String>,
    /// Last failed connect error text.
    pub(in crate::features) last_connect_failure_error: Option<String>,
    pub(in crate::features) security_auth_tab: SecurityAuthTab,
    pub(in crate::features) security_key_editor: Option<SecurityKeyEditorState>,
    pub(in crate::features) security_key_editor_focus: FocusHandle,
    pub(in crate::features) security_otp_editor: Option<SecurityOtpEditorState>,
    pub(in crate::features) security_otp_editor_focus: FocusHandle,
    pub(in crate::features) security_otp_qr_importing: bool,
    pub(in crate::features) security_password_editor: Option<SecurityPasswordEditorState>,
    pub(in crate::features) security_password_editor_focus: FocusHandle,
    pub(in crate::features) security_credential_editor: Option<SecurityCredentialEditorState>,
    pub(in crate::features) security_credential_editor_focus: FocusHandle,
    pub(in crate::features) security_delete_confirm: Option<SecurityDeleteConfirmState>,
    pub(in crate::features) security_otp_codes: HashMap<String, String>,
    pub(in crate::features) security_revealed_passwords: HashMap<String, String>,
    pub(in crate::features) security_revealed_credentials: HashMap<String, String>,
    pub(in crate::features) security_status: String,
    pub(in crate::features) security_secrets_unlocked: bool,
    pub(in crate::features) security_unlock_prompt_open: bool,
    pub(in crate::features) security_master_required_prompt_open: bool,
    pub(in crate::features) security_unlock_draft: String,
    pub(in crate::features) security_unlock_marked_text: String,
    pub(in crate::features) security_unlock_error: Option<String>,
    pub(in crate::features) security_unlock_pending_action: Option<SecurityUnlockAction>,
    pub(in crate::features) security_unlock_focus: FocusHandle,
    /// Legacy/global active pane tree view: mirrors the active tab's per-tab root when split.
    pub(in crate::features) workspace_split: Option<WorkspaceSplitState>,
    pub(in crate::features) workspace_split_resize: Option<WorkspaceSplitResizeState>,
    /// Per-tab pane trees keyed by tab-root session id (Tauri `Tab.root`).
    pub(in crate::features) session_pane_roots: HashMap<String, WorkspacePaneNode>,
    /// Leaf session id → owning tab-root session id (hidden from tab strip when secondary).
    pub(in crate::features) session_tab_owner: HashMap<String, String>,
    /// Tauri-style multi-leaf tab window layout (optional; None = flat tab strip).
    pub(in crate::features) terminal_windows: Option<TerminalWindowNode>,
    pub(in crate::features) focused_terminal_window_leaf_id: Option<String>,
    /// Active tab-dock drop target while dragging a session tab over a multi-leaf window.
    pub(in crate::features) terminal_window_drop: Option<(String, TabDockZone)>,
    /// Whether we already attempted startup restore of multi-leaf layout.
    pub(in crate::features) terminal_windows_restored: bool,
    /// Whether we already attempted startup restore of global workspace pane splits.
    pub(in crate::features) workspace_pane_layout_restored: bool,
    pub(in crate::features) startup_restore_complete: bool,
    pub(in crate::features) is_locked: bool,
    pub(in crate::features) last_user_activity_at: Instant,
}
