use super::*;

pub struct NyaTermApp {
    pub(in crate::ui::view) runtime: AppRuntime,
    pub(in crate::ui::view) services: NativeServices,
    pub(in crate::ui::view) inventory: MigrationInventory,
    pub(in crate::ui::view) connections: Vec<SavedConnection>,
    pub(in crate::ui::view) connection_groups: Vec<Group>,
    pub(in crate::ui::view) connection_search_draft: String,
    pub(in crate::ui::view) connection_search_focus: FocusHandle,
    pub(in crate::ui::view) connection_sort_mode: ConnectionSortMode,
    pub(in crate::ui::view) connections_more_menu_open: bool,
    pub(in crate::ui::view) connection_context_menu: Option<ConnectionContextMenuState>,
    pub(in crate::ui::view) connection_group_context_menu: Option<ConnectionGroupContextMenuState>,
    pub(in crate::ui::view) hovered_connection_id: Option<String>,
    pub(in crate::ui::view) connection_details_tooltip_id: Option<String>,
    pub(in crate::ui::view) connection_drop_target: Option<crate::ui::view::ConnectionDropTarget>,
    pub(in crate::ui::view) ai_execution_menu_open: bool,
    pub(in crate::ui::view) hovered_connection_group_id: Option<String>,
    pub(in crate::ui::view) expanded_connection_groups: HashSet<String>,
    pub(in crate::ui::view) connection_list_offset: usize,
    pub(in crate::ui::view) connection_editor: Option<ConnectionEditorState>,
    pub(in crate::ui::view) connection_editor_focus: FocusHandle,
    pub(in crate::ui::view) connection_group_editor: Option<ConnectionGroupEditorState>,
    pub(in crate::ui::view) connection_group_editor_focus: FocusHandle,
    pub(in crate::ui::view) connection_delete_confirm: Option<ConnectionDeleteConfirmState>,
    pub(in crate::ui::view) connection_group_delete_confirm: Option<ConnectionGroupDeleteConfirmState>,
    pub(in crate::ui::view) connection_ssh_keys: Vec<SshKey>,
    pub(in crate::ui::view) connection_otp_entries: Vec<OtpEntry>,
    pub(in crate::ui::view) connection_saved_passwords: Vec<SavedPassword>,
    pub(in crate::ui::view) connection_saved_credentials: Vec<SavedCredential>,
    pub(in crate::ui::view) connection_serial_ports: Vec<String>,
    pub(in crate::ui::view) tunnels: Vec<TunnelConfig>,
    pub(in crate::ui::view) tunnel_groups: Vec<TunnelGroup>,
    pub(in crate::ui::view) proxies: Vec<ProxyConfig>,
    pub(in crate::ui::view) proxy_groups: Vec<ProxyGroup>,
    pub(in crate::ui::view) network_tab: NetworkTab,
    pub(in crate::ui::view) network_delete_confirm: Option<NetworkDeleteConfirmState>,
    pub(in crate::ui::view) network_group_editor: Option<NetworkGroupEditorState>,
    pub(in crate::ui::view) network_group_delete_confirm: Option<NetworkGroupDeleteConfirmState>,
    pub(in crate::ui::view) network_move_picker: Option<NetworkMovePickerState>,
    pub(in crate::ui::view) network_expanded_sections: HashSet<String>,
    pub(in crate::ui::view) network_tunnel_editor: Option<NetworkTunnelEditorState>,
    pub(in crate::ui::view) network_proxy_editor: Option<NetworkProxyEditorState>,
    pub(in crate::ui::view) network_group_editor_focus: FocusHandle,
    pub(in crate::ui::view) network_tunnel_editor_focus: FocusHandle,
    pub(in crate::ui::view) network_proxy_editor_focus: FocusHandle,
    pub(in crate::ui::view) tunnel_search_draft: String,
    pub(in crate::ui::view) tunnel_search_focus: FocusHandle,
    pub(in crate::ui::view) proxy_search_draft: String,
    pub(in crate::ui::view) proxy_search_focus: FocusHandle,
    pub(in crate::ui::view) selected_connection_ids: HashSet<String>,
    pub(in crate::ui::view) last_selected_connection_id: Option<String>,
    pub(in crate::ui::view) quick_commands: Vec<QuickCommand>,
    pub(in crate::ui::view) quick_command_categories: Vec<QuickCommandCategory>,
    pub(in crate::ui::view) quick_command_search_draft: String,
    pub(in crate::ui::view) quick_command_search_focus: FocusHandle,
    pub(in crate::ui::view) quick_command_selected_category: String,
    pub(in crate::ui::view) quick_command_sort_mode: QuickCommandSortMode,
    pub(in crate::ui::view) quick_command_view_mode: QuickCommandViewMode,
    pub(in crate::ui::view) quick_command_editor: Option<QuickCommandEditorState>,
    pub(in crate::ui::view) quick_command_delete: Option<QuickCommandDeleteState>,
    pub(in crate::ui::view) quick_command_details: Option<QuickCommandDetailsState>,
    pub(in crate::ui::view) quick_command_category_delete: Option<QuickCommandCategoryDeleteState>,
    pub(in crate::ui::view) quick_command_category_rename: Option<QuickCommandCategoryRenameState>,
    pub(in crate::ui::view) quick_command_variable_prompt: Option<QuickCommandVariablePromptState>,
    pub(in crate::ui::view) quick_command_import_dialog_open: bool,
    pub(in crate::ui::view) quick_command_import_path_prompt:
        Option<QuickCommandImportPathPromptKind>,
    pub(in crate::ui::view) quick_command_editor_focus: FocusHandle,
    pub(in crate::ui::view) quick_command_details_focus: FocusHandle,
    pub(in crate::ui::view) quick_command_category_rename_focus: FocusHandle,
    pub(in crate::ui::view) quick_command_variable_focus: FocusHandle,
    pub(in crate::ui::view) quick_command_import_focus: FocusHandle,
    pub(in crate::ui::view) command_history: Vec<CommandHistoryEntry>,
    pub(in crate::ui::view) session_command_history: HashMap<String, Vec<String>>,
    pub(in crate::ui::view) command_search_draft: String,
    /// Inline terminal command suggestions (Tauri CommandSuggestions).
    pub(in crate::ui::view) command_suggestions: Option<CommandSuggestionState>,
    /// Local terminal input tracker for inline suggestions (Tauri terminalInputTracker).
    pub(in crate::ui::view) command_input_tracker: TerminalInputState,
    /// Hide suggestions after interactive programs (vim/htop/less/...) until Ctrl+C/q.
    pub(in crate::ui::view) command_suggestions_suppressed: bool,
    /// Command captured from tracker at Enter, consumed by history recording.
    pub(in crate::ui::view) pending_command_history_entry: Option<String>,
    /// Bumps to cancel in-flight 80ms suggestion search timers (Tauri searchTimer).
    pub(in crate::ui::view) command_suggestion_search_gen: u64,
    /// Terminal-output credential autofill panel (Tauri CredentialSuggestions).
    pub(in crate::ui::view) credential_suggestions: Option<CredentialSuggestionState>,
    pub(in crate::ui::view) credential_autofill_buffer: String,
    pub(in crate::ui::view) credential_autofill_recent: HashMap<String, u64>,
    pub(in crate::ui::view) credential_autofill_pending: Option<PendingCredentialAutofill>,
    pub(in crate::ui::view) credential_autofill_sending: bool,
    /// Suppress command suggestions while a password/username prompt is active.
    pub(in crate::ui::view) credential_prompt_input_until_ms: u64,

    pub(in crate::ui::view) command_search_focus: FocusHandle,
    pub(in crate::ui::view) active_sessions_search_draft: String,
    pub(in crate::ui::view) active_sessions_search_focus: FocusHandle,
    /// Session id with open reconnect/disconnect overflow menu (Tauri ActiveSessions more menu).
    pub(in crate::ui::view) active_session_menu_id: Option<String>,
    /// Per-session reconnect/disconnect busy state ("reconnect" | "disconnect").
    pub(in crate::ui::view) active_session_busy_actions: HashMap<String, String>,
    pub(in crate::ui::view) quick_switch_open: bool,
    pub(in crate::ui::view) quick_switch_query: String,
    pub(in crate::ui::view) quick_switch_selected_index: usize,
    pub(in crate::ui::view) quick_switch_focus: FocusHandle,
    pub(in crate::ui::view) terminal_search_open: bool,
    pub(in crate::ui::view) terminal_search_query: String,
    pub(in crate::ui::view) terminal_search_focus: FocusHandle,
    pub(in crate::ui::view) terminal_search_mode: TerminalSearchMode,
    pub(in crate::ui::view) terminal_search_case_sensitive: bool,
    pub(in crate::ui::view) terminal_search_regex: bool,
    pub(in crate::ui::view) terminal_search_whole_word: bool,
    pub(in crate::ui::view) terminal_search_active_index: usize,
    /// Which search engine row is focused for name/url editing (Settings → Search).
    pub(in crate::ui::view) search_engine_edit_index: Option<usize>,
    pub(in crate::ui::view) search_engine_expanded_index: Option<usize>,
    pub(in crate::ui::view) search_engine_edit_field: SearchEngineEditorField,
    pub(in crate::ui::view) search_engine_focus: FocusHandle,
    /// Dragging the terminal scrollback scrollbar thumb.
    pub(in crate::ui::view) terminal_scrollbar_dragging: bool,
    pub(in crate::ui::view) terminal_actions_open: bool,
    pub(in crate::ui::view) terminal_actions_focus: FocusHandle,
    pub(in crate::ui::view) terminal_context_menu: Option<TerminalContextMenuState>,
    pub(in crate::ui::view) action_link_menu: Option<ActionLinkMenuState>,
    pub(in crate::ui::view) action_link_tooltip: Option<ActionLinkTooltipState>,
    /// Pending action-link hover (Tauri 250ms delay before showing tooltip).
    pub(in crate::ui::view) action_link_hover_pending: Option<(String, Instant, ActionLinkTooltipState)>,

    pub(in crate::ui::view) translation_dialog: Option<TranslationDialogState>,
    pub(in crate::ui::view) bottom_panel: BottomPanelMode,
    pub(in crate::ui::view) send_command_draft: String,
    pub(in crate::ui::view) send_command_focus: FocusHandle,
    pub(in crate::ui::view) send_command_data_type: SendCommandDataType,
    pub(in crate::ui::view) send_command_mode: SendCommandMode,
    pub(in crate::ui::view) send_command_count: Option<u32>,
    pub(in crate::ui::view) send_command_interval_seconds: f64,
    pub(in crate::ui::view) send_command_line_ending: SendCommandLineEnding,
    pub(in crate::ui::view) send_command_target: SendCommandTarget,
    pub(in crate::ui::view) send_command_sending: bool,
    pub(in crate::ui::view) send_command_cancel: Option<Arc<AtomicBool>>,
    pub(in crate::ui::view) send_command_progress_completed: u32,
    pub(in crate::ui::view) send_command_progress_total: u32,
    pub(in crate::ui::view) send_command_progress_round: u32,
    pub(in crate::ui::view) send_command_progress_rounds: u32,
    pub(in crate::ui::view) sync_groups: Vec<SyncInputGroup>,
    pub(in crate::ui::view) sync_groups_open: bool,
    pub(in crate::ui::view) sync_groups_focus: FocusHandle,
    pub(in crate::ui::view) sync_groups_selected_id: Option<String>,
    /// Broadcast keyboard input to every live session (Tauri broadcastToAll).
    pub(in crate::ui::view) broadcast_to_all: bool,
    pub(in crate::ui::view) keyword_highlights: KeywordHighlightConfig,
    pub(in crate::ui::view) keyword_highlight_expanded_id: Option<String>,
    pub(in crate::ui::view) keyword_highlight_edit_id: Option<String>,
    pub(in crate::ui::view) keyword_highlight_edit_field: KeywordHighlightEditorField,
    pub(in crate::ui::view) keyword_highlight_focus: FocusHandle,
    pub(in crate::ui::view) settings: AppSettingsSummary,
    pub(in crate::ui::view) keybinding_recording_id: Option<String>,
    pub(in crate::ui::view) keybinding_pending_keys: Option<String>,
    pub(in crate::ui::view) keybinding_search_draft: String,
    pub(in crate::ui::view) keybinding_search_focus: FocusHandle,
    pub(in crate::ui::view) keybindings_focus: FocusHandle,
    pub(in crate::ui::view) store_status: StoreStatus,
    pub(in crate::ui::view) session_manager: Arc<SessionManager>,
    pub(in crate::ui::view) recording_manager: Arc<RecordingManager>,
    pub(in crate::ui::view) recording_search_draft: String,
    pub(in crate::ui::view) recording_search_focus: FocusHandle,
    pub(in crate::ui::view) session_start_tx: mpsc::Sender<SessionStartResult>,
    pub(in crate::ui::view) session_start_rx: mpsc::Receiver<SessionStartResult>,
    pub(in crate::ui::view) tunnel_manager: Arc<SshTunnelManager>,
    pub(in crate::ui::view) tunnel_tx: mpsc::Sender<TunnelJobResult>,
    pub(in crate::ui::view) tunnel_rx: mpsc::Receiver<TunnelJobResult>,
    pub(in crate::ui::view) pending_tunnels: Vec<String>,
    pub(in crate::ui::view) process_tx: mpsc::Sender<ProcessJobResult>,
    pub(in crate::ui::view) process_rx: mpsc::Receiver<ProcessJobResult>,
    pub(in crate::ui::view) processes: Vec<RemoteProcess>,
    pub(in crate::ui::view) process_status: String,
    pub(in crate::ui::view) process_pending: bool,
    pub(in crate::ui::view) process_last_refresh_at: Option<Instant>,
    pub(in crate::ui::view) process_search_draft: String,
    pub(in crate::ui::view) process_search_focus: FocusHandle,
    pub(in crate::ui::view) process_sort_key: RemoteProcessSortKey,
    pub(in crate::ui::view) process_sort_direction: RemoteProcessSortDirection,
    pub(in crate::ui::view) process_list_offset: usize,
    pub(in crate::ui::view) docker_list_offset: usize,
    pub(in crate::ui::view) docker_resource_list_offset: usize,
    pub(in crate::ui::view) send_command_hex_scroll_x: f32,
    pub(in crate::ui::view) send_command_hex_scroll_y: f32,
    pub(in crate::ui::view) process_selected_pid: Option<u32>,
    pub(in crate::ui::view) process_menu_pid: Option<u32>,
    pub(in crate::ui::view) process_nice_draft: String,
    pub(in crate::ui::view) process_nice_focus: FocusHandle,
    pub(in crate::ui::view) process_signal_confirm: Option<RemoteProcessSignalConfirmState>,
    pub(in crate::ui::view) stats_tx: mpsc::Sender<StatsJobResult>,
    pub(in crate::ui::view) stats_rx: mpsc::Receiver<StatsJobResult>,
    pub(in crate::ui::view) remote_stats: Option<RemoteStats>,
    pub(in crate::ui::view) stats_status: String,
    pub(in crate::ui::view) stats_pending: bool,
    pub(in crate::ui::view) stats_last_refresh_at: Option<Instant>,
    pub(in crate::ui::view) stats_cpu_expanded: bool,
    pub(in crate::ui::view) translate_tx: mpsc::Sender<TranslateJobResult>,
    pub(in crate::ui::view) translate_rx: mpsc::Receiver<TranslateJobResult>,
    pub(in crate::ui::view) translate_provider: String,
    pub(in crate::ui::view) translation_settings: TranslationSettings,
    pub(in crate::ui::view) translation_secret_draft: TranslationSecretDraft,
    pub(in crate::ui::view) translate_target_language: String,
    pub(in crate::ui::view) translate_input: String,
    pub(in crate::ui::view) translate_result: Option<TranslateResult>,
    pub(in crate::ui::view) translate_status: String,
    pub(in crate::ui::view) translate_pending: bool,
    pub(in crate::ui::view) translate_focus: FocusHandle,
    pub(in crate::ui::view) translate_focused_field: TranslateInputField,
    pub(in crate::ui::view) update_tx: mpsc::Sender<UpdateJobResult>,
    pub(in crate::ui::view) update_rx: mpsc::Receiver<UpdateJobResult>,
    pub(in crate::ui::view) update_status: String,
    pub(in crate::ui::view) update_info: Option<NativeUpdateInfo>,
    pub(in crate::ui::view) update_pending: bool,
    pub(in crate::ui::view) docker_tx: mpsc::Sender<DockerJobResult>,
    pub(in crate::ui::view) docker_rx: mpsc::Receiver<DockerJobResult>,
    pub(in crate::ui::view) docker_overview: Option<RemoteDockerOverview>,
    pub(in crate::ui::view) docker_status: String,
    pub(in crate::ui::view) docker_pending: bool,
    pub(in crate::ui::view) docker_last_refresh_at: Option<Instant>,
    pub(in crate::ui::view) docker_logs: String,
    pub(in crate::ui::view) docker_logs_container_id: Option<String>,
    pub(in crate::ui::view) docker_details: Option<DockerContainerDetails>,
    pub(in crate::ui::view) docker_details_container_id: Option<String>,
    pub(in crate::ui::view) docker_details_last_refresh_at: Option<Instant>,
    pub(in crate::ui::view) docker_confirm: Option<DockerConfirmState>,
    pub(in crate::ui::view) docker_container_menu_id: Option<String>,
    pub(in crate::ui::view) docker_compose_menu_id: Option<String>,
    pub(in crate::ui::view) docker_tab: DockerTab,
    pub(in crate::ui::view) docker_search_draft: String,
    pub(in crate::ui::view) docker_search_focus: FocusHandle,
    pub(in crate::ui::view) docker_compose_expanded: HashSet<String>,
    pub(in crate::ui::view) docker_compose_services: HashMap<String, Vec<DockerComposeService>>,
    pub(in crate::ui::view) docker_compose_service_errors: HashMap<String, String>,
    pub(in crate::ui::view) transfer_tx: mpsc::Sender<TransferJobResult>,
    pub(in crate::ui::view) transfer_rx: mpsc::Receiver<TransferJobResult>,
    pub(in crate::ui::view) transfer_jobs: Vec<TransferJobState>,
    pub(in crate::ui::view) transfer_selected_job_id: Option<String>,
    pub(in crate::ui::view) transfer_job_delete: Option<TransferJobDeleteState>,
    pub(in crate::ui::view) transfer_remote_path: String,
    pub(in crate::ui::view) transfer_local_path: String,
    pub(in crate::ui::view) transfer_duplicate_policy: SftpDuplicatePolicy,
    pub(in crate::ui::view) transfer_path_prompt: Option<TransferPathPromptKind>,
    pub(in crate::ui::view) transfer_browser_path: String,
    pub(in crate::ui::view) transfer_browser_home_dir: String,
    pub(in crate::ui::view) transfer_browser_home_dir_pending: bool,
    pub(in crate::ui::view) transfer_browser_path_draft: String,
    pub(in crate::ui::view) transfer_browser_path_editing: bool,
    pub(in crate::ui::view) transfer_browser_entries: Vec<SftpFileEntry>,
    pub(in crate::ui::view) transfer_browser_status: String,
    pub(in crate::ui::view) transfer_browser_search: String,
    pub(in crate::ui::view) transfer_browser_list_offset: usize,
    pub(in crate::ui::view) transfer_browser_search_expanded: bool,
    pub(in crate::ui::view) transfer_browser_history: VecDeque<String>,
    pub(in crate::ui::view) transfer_browser_history_index: usize,
    pub(in crate::ui::view) transfer_browser_visited_history: VecDeque<String>,
    pub(in crate::ui::view) transfer_browser_session_cache:
        HashMap<String, TransferBrowserSessionCacheState>,
    pub(in crate::ui::view) transfer_auto_sync_cwd_last_at: Option<Instant>,
    pub(in crate::ui::view) transfer_browser_favorites: VecDeque<String>,
    pub(in crate::ui::view) transfer_browser_sort_column: TransferBrowserSortColumn,
    pub(in crate::ui::view) transfer_browser_sort_direction: TransferBrowserSortDirection,
    pub(in crate::ui::view) transfer_browser_column_widths: TransferBrowserColumnWidths,
    pub(in crate::ui::view) transfer_browser_column_resize:
        Option<TransferBrowserColumnResizeState>,
    pub(in crate::ui::view) transfer_selected_remote_path: Option<String>,
    pub(in crate::ui::view) transfer_selected_remote_paths: HashSet<String>,
    pub(in crate::ui::view) transfer_browser_drag_selection:
        Option<TransferBrowserDragSelectionState>,
    pub(in crate::ui::view) transfer_browser_pending_rename:
        Option<TransferBrowserPendingRenameState>,
    pub(in crate::ui::view) transfer_browser_pending_rename_token: u64,
    pub(in crate::ui::view) transfer_browser_context_menu: Option<TransferBrowserContextMenuState>,
    pub(in crate::ui::view) transfer_browser_favorites_menu:
        Option<TransferBrowserFavoritesMenuState>,
    pub(in crate::ui::view) transfer_browser_upload_menu: Option<TransferBrowserUploadMenuState>,
    pub(in crate::ui::view) transfer_rename: Option<TransferRenameState>,
    pub(in crate::ui::view) transfer_rename_focus_pending: bool,
    pub(in crate::ui::view) transfer_move: Option<TransferMoveState>,
    pub(in crate::ui::view) transfer_delete: Option<TransferDeleteState>,
    pub(in crate::ui::view) transfer_new_folder: Option<TransferNewFolderState>,
    pub(in crate::ui::view) transfer_new_file: Option<TransferNewFileState>,
    pub(in crate::ui::view) transfer_new_symlink: Option<TransferNewSymlinkState>,
    pub(in crate::ui::view) transfer_properties: Option<TransferPropertiesState>,
    pub(in crate::ui::view) transfer_editor: Option<TransferEditorState>,
    pub(in crate::ui::view) transfer_unknown_file: Option<TransferUnknownFileState>,
    pub(in crate::ui::view) transfer_external_sync_prompt: Option<TransferExternalSyncPromptState>,
    pub(in crate::ui::view) transfer_external_always_uploads: HashSet<String>,
    pub(in crate::ui::view) recording_path_prompt: Option<RecordingPathPromptKind>,
    pub(in crate::ui::view) config_path_prompt: Option<ConfigPathPromptKind>,
    pub(in crate::ui::view) diagnostics_path_prompt: Option<DiagnosticsPathPromptKind>,
    pub(in crate::ui::view) keyword_highlight_path_prompt: Option<KeywordHighlightPathPromptKind>,
    pub(in crate::ui::view) active_snapshot_password_prompt: Option<SnapshotPasswordPromptState>,
    pub(in crate::ui::view) cloud_sync_settings: CloudSyncSettings,
    pub(in crate::ui::view) cloud_sync_state: CloudSyncState,
    pub(in crate::ui::view) cloud_sync_history: Vec<CloudSyncHistoryEntry>,
    pub(in crate::ui::view) cloud_sync_history_expanded: HashSet<String>,
    pub(in crate::ui::view) cloud_sync_conflict: Option<CloudSyncConflictState>,
    pub(in crate::ui::view) cloud_sync_secret_draft: CloudSyncSecretDraft,
    pub(in crate::ui::view) cloud_sync_status: String,
    pub(in crate::ui::view) cloud_sync_focus: FocusHandle,
    pub(in crate::ui::view) cloud_sync_focused_field: CloudSyncInputField,
    pub(in crate::ui::view) ai_settings: AiSettings,
    pub(in crate::ui::view) ai_model_draft: String,
    pub(in crate::ui::view) ai_base_url_draft: String,
    pub(in crate::ui::view) ai_secret_draft: String,
    pub(in crate::ui::view) ai_status: String,
    pub(in crate::ui::view) ai_session_count: usize,
    pub(in crate::ui::view) ai_message_count: usize,
    pub(in crate::ui::view) ai_audit_count: usize,
    pub(in crate::ui::view) ai_discovery_tx: mpsc::Sender<AiDiscoveryJobResult>,
    pub(in crate::ui::view) ai_discovery_rx: mpsc::Receiver<AiDiscoveryJobResult>,
    pub(in crate::ui::view) ai_discovery_pending: bool,
    pub(in crate::ui::view) ai_chat_tx: mpsc::Sender<AiChatWorkerEvent>,
    pub(in crate::ui::view) ai_chat_rx: mpsc::Receiver<AiChatWorkerEvent>,
    pub(in crate::ui::view) ai_chat_pending: bool,
    pub(in crate::ui::view) ai_chat_job_id: u64,
    pub(in crate::ui::view) ai_chat_cancel: Option<Arc<AtomicBool>>,
    pub(in crate::ui::view) ai_chat_session_id: String,
    pub(in crate::ui::view) ai_prompt_draft: String,
    pub(in crate::ui::view) ai_prepared_request: Option<AiPreparedRequest>,
    pub(in crate::ui::view) ai_response_preview: String,
    pub(in crate::ui::view) ai_chat_messages: Vec<AiMessage>,
    pub(in crate::ui::view) ai_streaming_assistant_id: Option<String>,
    pub(in crate::ui::view) ai_history_open: bool,
    pub(in crate::ui::view) ai_history_query: String,
    pub(in crate::ui::view) ai_history_search_focus: FocusHandle,
    pub(in crate::ui::view) ai_sessions: Vec<AiSession>,
    pub(in crate::ui::view) ai_command_cards: Vec<AiCommandCard>,
    pub(in crate::ui::view) ai_agent_task_prompt: Option<String>,
    pub(in crate::ui::view) ai_agent_step_index: u16,
    pub(in crate::ui::view) ai_agent_loop: Option<AiAgentLoopState>,
    pub(in crate::ui::view) ai_agent_capture: AgentOutputCaptureProcessor,
    pub(in crate::ui::view) ai_agent_steps: Vec<AiAgentStepView>,
    pub(in crate::ui::view) ai_agent_thought_expanded: HashSet<u16>,
    pub(in crate::ui::view) ai_agent_output_expanded: HashSet<u16>,
    pub(in crate::ui::view) ai_chat_focus: FocusHandle,
    pub(in crate::ui::view) ai_chat_focus_pending: bool,
    pub(in crate::ui::view) ai_focus: FocusHandle,
    pub(in crate::ui::view) ai_focused_field: AiInputField,
    pub(in crate::ui::view) ai_action_expanded: Option<(AiActionListKind, String)>,
    pub(in crate::ui::view) ai_action_edit: Option<(AiActionListKind, String, AiActionEditorField)>,
    pub(in crate::ui::view) ai_action_focus: FocusHandle,
    pub(in crate::ui::view) ai_model_collapsed_groups: HashSet<String>,
    pub(in crate::ui::view) ai_manual_model_drafts: HashMap<String, String>,
    pub(in crate::ui::view) ai_manual_model_focus: FocusHandle,
    pub(in crate::ui::view) ai_manual_model_edit_group: Option<String>,
    /// Expanded API-key credential card in Settings → AI Models (Tauri AiModelsTab).
    pub(in crate::ui::view) ai_credential_expanded_id: Option<String>,
    pub(in crate::ui::view) ai_credential_edit: Option<(String, AiCredentialEditorField)>,
    pub(in crate::ui::view) ai_credential_focus: FocusHandle,
    /// Per-credential API-key drafts; empty means keep the stored secret.
    pub(in crate::ui::view) ai_credential_secret_drafts: HashMap<String, String>,
    pub(in crate::ui::view) transfer_focus: FocusHandle,
    pub(in crate::ui::view) transfer_queue_focus: FocusHandle,
    pub(in crate::ui::view) transfer_browser_focus: FocusHandle,
    pub(in crate::ui::view) transfer_browser_path_focus: FocusHandle,
    pub(in crate::ui::view) transfer_browser_search_focus: FocusHandle,
    pub(in crate::ui::view) transfer_rename_focus: FocusHandle,
    pub(in crate::ui::view) transfer_move_focus: FocusHandle,
    pub(in crate::ui::view) transfer_delete_focus: FocusHandle,
    pub(in crate::ui::view) transfer_new_folder_focus: FocusHandle,
    pub(in crate::ui::view) transfer_new_file_focus: FocusHandle,
    pub(in crate::ui::view) transfer_new_symlink_focus: FocusHandle,
    pub(in crate::ui::view) transfer_properties_focus: FocusHandle,
    pub(in crate::ui::view) transfer_editor_focus: FocusHandle,
    pub(in crate::ui::view) transfer_unknown_file_focus: FocusHandle,
    pub(in crate::ui::view) transfer_external_sync_focus: FocusHandle,
    pub(in crate::ui::view) transfer_job_delete_focus: FocusHandle,
    pub(in crate::ui::view) transfer_default_editor_focus: FocusHandle,
    pub(in crate::ui::view) transfer_focused_field: TransferInputField,
    pub(in crate::ui::view) duplicate_prompts: Arc<SftpDuplicatePromptBroker>,
    pub(in crate::ui::view) active_duplicate_prompt: Option<SftpDuplicatePromptState>,
    pub(in crate::ui::view) pending_session_name: Option<String>,
    pub(in crate::ui::view) pending_ssh_config: Option<SshSessionConfig>,
    pub(in crate::ui::view) pending_ai_execution_profile: AiExecutionProfile,
    pub(in crate::ui::view) pending_session_custom_name: Option<String>,
    pub(in crate::ui::view) pending_session_tab_color: Option<u32>,
    pub(in crate::ui::view) pending_session_after_id: Option<String>,
    pub(in crate::ui::view) pending_session_insert_index: Option<usize>,
    pub(in crate::ui::view) pending_terminal_seed_output: Option<String>,
    /// Disconnected session id being replaced by an in-flight reconnect.
    pub(in crate::ui::view) pending_reconnect_replace_id: Option<String>,
    pub(in crate::ui::view) pending_startup_command: Option<StartupCommandRequest>,
    pub(in crate::ui::view) pending_session_multiplex_key: Option<String>,
    pub(in crate::ui::view) pending_source_connection_id: Option<String>,
    pub(in crate::ui::view) pending_workspace_split: Option<(WorkspaceSplitDirection, String)>,
    pub(in crate::ui::view) host_key_prompts: Arc<HostKeyPromptBroker>,
    pub(in crate::ui::view) active_host_key_prompt: Option<HostKeyPromptRequest>,
    pub(in crate::ui::view) credential_prompts: Arc<CredentialPromptBroker>,
    pub(in crate::ui::view) active_credential_prompt: Option<CredentialPromptState>,
    pub(in crate::ui::view) credential_focus: FocusHandle,
    pub(in crate::ui::view) snapshot_password_focus: FocusHandle,
    pub(in crate::ui::view) otp_provider: Arc<NativeOtpProvider>,
    pub(in crate::ui::view) active_session_id: Option<String>,
    pub(in crate::ui::view) active_ssh_config: Option<SshSessionConfig>,
    pub(in crate::ui::view) active_ai_execution_profile: AiExecutionProfile,
    pub(in crate::ui::view) session_order: Vec<String>,
    pub(in crate::ui::view) session_metadata: HashMap<String, SessionRuntimeMetadata>,
    pub(in crate::ui::view) session_custom_names: HashMap<String, String>,
    /// OSC 0/2 titles from the session PTY (fall back when no custom rename).
    pub(in crate::ui::view) session_dynamic_titles: HashMap<String, String>,
    /// Latest OSC 7 working directories per session.
    pub(in crate::ui::view) session_cwds: HashMap<String, String>,
    /// Per-session ZMODEM detector / transfer state (UI-layer interception).
    pub(in crate::ui::view) zmodem_sessions: HashMap<String, crate::ui::view::zmodem_runtime::ZmodemSessionState>,
    pub(in crate::ui::view) session_tab_colors: HashMap<String, u32>,
    pub(in crate::ui::view) ssh_multiplex_handles: HashMap<String, SshMultiplexHandle>,
    pub(in crate::ui::view) terminal_views: HashMap<String, TerminalViewState>,
    pub(in crate::ui::view) tab_actions_session_id: Option<String>,
    pub(in crate::ui::view) tab_actions_anchor: Option<(f32, f32)>,
    pub(in crate::ui::view) tab_actions_focus: FocusHandle,
    pub(in crate::ui::view) close_all_sessions_confirm_open: bool,
    pub(in crate::ui::view) pending_quit_after_close_all: bool,
    pub(in crate::ui::view) pending_window_quit: bool,
    pub(in crate::ui::view) close_all_sessions_confirm_focus: FocusHandle,
    pub(in crate::ui::view) rename_session_id: Option<String>,
    pub(in crate::ui::view) rename_draft: String,
    pub(in crate::ui::view) rename_focus: FocusHandle,
    pub(in crate::ui::view) color_picker_open: bool,
    pub(in crate::ui::view) color_picker_focus: FocusHandle,
    pub(in crate::ui::view) session_info_open: bool,
    pub(in crate::ui::view) session_info_focus: FocusHandle,
    pub(in crate::ui::view) startup_command_open: bool,
    pub(in crate::ui::view) startup_command_action: StartupCommandAction,
    pub(in crate::ui::view) startup_command_draft: String,
    pub(in crate::ui::view) startup_command_delay_ms: u64,
    pub(in crate::ui::view) startup_command_focus: FocusHandle,
    pub(in crate::ui::view) temporary_ssh_link_open: bool,
    pub(in crate::ui::view) temporary_ssh_link_draft: String,
    pub(in crate::ui::view) temporary_ssh_link_error: Option<String>,
    pub(in crate::ui::view) temporary_ssh_link_focus: FocusHandle,
    pub(in crate::ui::view) multi_line_paste: Option<MultiLinePasteDraft>,
    pub(in crate::ui::view) multi_line_paste_focus: FocusHandle,
    pub(in crate::ui::view) terminal_focus: FocusHandle,
    pub(in crate::ui::view) lock_focus: FocusHandle,
    pub(in crate::ui::view) lock_password_draft: String,
    pub(in crate::ui::view) lock_status: String,
    pub(in crate::ui::view) terminal_output: String,
    pub(in crate::ui::view) terminal_screen: TerminalScreen,
    /// Scroll offset for the fallback/global terminal screen (no session view).
    pub(in crate::ui::view) terminal_scroll_offset: usize,
    pub(in crate::ui::view) terminal_status: String,
    pub(in crate::ui::view) event_pump_started: bool,
    /// Toggles on the event pump when cursor blink is enabled.
    pub(in crate::ui::view) cursor_blink_on: bool,
    pub(in crate::ui::view) cursor_blink_tick: u8,
    /// Active visible-grid selection for the focused terminal surface.
    pub(in crate::ui::view) terminal_selection: Option<TerminalSelection>,
    /// True while the user is dragging a left-button text selection.
    pub(in crate::ui::view) terminal_selection_dragging: bool,
    /// Last painted bounds of the active terminal text area (window coords).
    pub(in crate::ui::view) terminal_surface_bounds: Option<gpui::Bounds<gpui::Pixels>>,
    /// Measured monospaced cell size (width, height) from the terminal font when available.
    pub(in crate::ui::view) terminal_cell_metrics: Option<(f32, f32)>,
    /// Remaining event-pump ticks for visual BEL flash (0 = off).
    pub(in crate::ui::view) visual_bell_ticks: u8,
    /// Session id currently under an external file drag (drop overlay).
    pub(in crate::ui::view) terminal_file_drop_hover: Option<String>,

    pub(in crate::ui::view) last_viewport_size: (f32, f32),
    pub(in crate::ui::view) selected_nav: NavItem,
    pub(in crate::ui::view) main_mode: MainMode,
    pub(in crate::ui::view) settings_active_tab: SettingsTab,
    pub(in crate::ui::view) active_left_panel: Option<NavItem>,
    pub(in crate::ui::view) active_right_panel: Option<NavItem>,
    pub(in crate::ui::view) left_open_panels: Vec<String>,
    pub(in crate::ui::view) right_open_panels: Vec<String>,
    pub(in crate::ui::view) panel_stack_sizes: HashMap<String, f32>,
    pub(in crate::ui::view) panel_multi_open: bool,
    pub(in crate::ui::view) right_focus: RightFocus,
    pub(in crate::ui::view) left_sidebar_collapsed: bool,
    pub(in crate::ui::view) right_inspector_collapsed: bool,
    pub(in crate::ui::view) left_panel_width: f32,
    pub(in crate::ui::view) right_panel_width: f32,
    pub(in crate::ui::view) transfer_panel_height: f32,
    pub(in crate::ui::view) panel_resize: Option<PanelResizeState>,
    pub(in crate::ui::view) transfer_height_resize: Option<TransferHeightResizeState>,
    pub(in crate::ui::view) panel_stack_resize: Option<PanelStackResizeState>,
    pub(in crate::ui::view) activity_bar_layout: ActivityBarLayoutState,
    pub(in crate::ui::view) activity_bar_context_menu: Option<ActivityBarContextMenuState>,
    pub(in crate::ui::view) title_menu_open: Option<TitleMenu>,
    /// Open-tabs overflow menu (Tauri TabBar expand-more when many tabs).
    pub(in crate::ui::view) open_tabs_menu_open: bool,
    /// New-session menu next to the tab strip + control.
    pub(in crate::ui::view) new_session_menu_open: bool,
    /// Horizontal scroll handle for the global session tab strip (scroll-into-view).
    pub(in crate::ui::view) session_tab_strip_scroll: ScrollHandle,
    /// Request scroll-into-view of the active tab on next paint (Tauri TabBar).
    pub(in crate::ui::view) session_tab_scroll_into_view_pending: bool,
    /// Last failed connect name (shown as ephemeral failed tab chrome).
    pub(in crate::ui::view) last_connect_failure_name: Option<String>,
    /// Last failed connect error text.
    pub(in crate::ui::view) last_connect_failure_error: Option<String>,
    pub(in crate::ui::view) security_auth_tab: SecurityAuthTab,
    pub(in crate::ui::view) security_key_editor: Option<SecurityKeyEditorState>,
    pub(in crate::ui::view) security_key_editor_focus: FocusHandle,
    pub(in crate::ui::view) security_otp_editor: Option<SecurityOtpEditorState>,
    pub(in crate::ui::view) security_otp_editor_focus: FocusHandle,
    pub(in crate::ui::view) security_password_editor: Option<SecurityPasswordEditorState>,
    pub(in crate::ui::view) security_password_editor_focus: FocusHandle,
    pub(in crate::ui::view) security_credential_editor: Option<SecurityCredentialEditorState>,
    pub(in crate::ui::view) security_credential_editor_focus: FocusHandle,
    pub(in crate::ui::view) security_delete_confirm: Option<SecurityDeleteConfirmState>,
    pub(in crate::ui::view) security_otp_codes: HashMap<String, String>,
    pub(in crate::ui::view) security_revealed_passwords: HashMap<String, String>,
    pub(in crate::ui::view) security_revealed_credentials: HashMap<String, String>,
    pub(in crate::ui::view) security_status: String,
    pub(in crate::ui::view) security_secrets_unlocked: bool,
    pub(in crate::ui::view) security_unlock_prompt_open: bool,
    pub(in crate::ui::view) security_unlock_draft: String,
    pub(in crate::ui::view) security_unlock_error: Option<String>,
    pub(in crate::ui::view) security_unlock_focus: FocusHandle,
    /// Legacy/global active pane tree view: mirrors the active tab's per-tab root when split.
    pub(in crate::ui::view) workspace_split: Option<WorkspaceSplitState>,
    pub(in crate::ui::view) workspace_split_resize: Option<WorkspaceSplitResizeState>,
    /// Per-tab pane trees keyed by tab-root session id (Tauri `Tab.root`).
    pub(in crate::ui::view) session_pane_roots: HashMap<String, WorkspacePaneNode>,
    /// Leaf session id → owning tab-root session id (hidden from tab strip when secondary).
    pub(in crate::ui::view) session_tab_owner: HashMap<String, String>,
    /// Tauri-style multi-leaf tab window layout (optional; None = flat tab strip).
    pub(in crate::ui::view) terminal_windows: Option<TerminalWindowNode>,
    pub(in crate::ui::view) focused_terminal_window_leaf_id: Option<String>,
    /// Active tab-dock drop target while dragging a session tab over a multi-leaf window.
    pub(in crate::ui::view) terminal_window_drop: Option<(String, TabDockZone)>,
    /// Whether we already attempted startup restore of multi-leaf layout.
    pub(in crate::ui::view) terminal_windows_restored: bool,
    /// Whether we already attempted startup restore of global workspace pane splits.
    pub(in crate::ui::view) workspace_pane_layout_restored: bool,
    pub(in crate::ui::view) open_tabs_restored: bool,
    pub(in crate::ui::view) startup_restore_complete: bool,
    pub(in crate::ui::view) startup_restore_queue: Vec<nyaterm_domain::RestorableOpenTab>,
    /// Per-tab pane layouts extracted from open_tabs[].root (indexes into expanded session order).
    pub(in crate::ui::view) startup_pending_pane_layouts:
        Vec<nyaterm_domain::RestorableWorkspacePaneNode>,
    /// Optional active leaf session indexes (into expanded order) requested after restore.
    pub(in crate::ui::view) startup_pending_active_pane_indexes: Vec<usize>,
    pub(in crate::ui::view) is_locked: bool,
    pub(in crate::ui::view) last_user_activity_at: Instant,
}

impl NyaTermApp {
    pub fn new(runtime: AppRuntime, cx: &mut Context<Self>) -> Self {
        let legacy = LegacyProject::new(LEGACY_ROOT);
        let inventory = nyaterm_migration::inventory(&legacy);
        let (session_start_tx, session_start_rx) = mpsc::channel();
        let (tunnel_tx, tunnel_rx) = mpsc::channel();
        let (process_tx, process_rx) = mpsc::channel();
        let (stats_tx, stats_rx) = mpsc::channel();
        let (translate_tx, translate_rx) = mpsc::channel();
        let (update_tx, update_rx) = mpsc::channel();
        let (docker_tx, docker_rx) = mpsc::channel();
        let (transfer_tx, transfer_rx) = mpsc::channel();
        let (ai_discovery_tx, ai_discovery_rx) = mpsc::channel();
        let (ai_chat_tx, ai_chat_rx) = mpsc::channel();
        let (
            connections,
            connection_groups,
            connection_ssh_keys,
            connection_otp_entries,
            connection_saved_passwords,
            connection_saved_credentials,
            tunnels,
            tunnel_groups,
            proxies,
            proxy_groups,
            quick_commands,
            quick_command_categories,
            command_history,
            keyword_highlights,
            settings,
            store_status,
            cloud_sync_settings,
            cloud_sync_state,
            translation_settings,
            ai_settings,
            ai_session_count,
            ai_message_count,
            ai_audit_count,
        ) = match ConnectionStore::open_with_portable_key_path(
            runtime.config_dir(),
            runtime.portable_key_path().map(ToOwned::to_owned),
        ) {
            Ok(store) => {
                let path = store.db_path().display().to_string();
                match store.load_sessions() {
                    Ok(config) => {
                        let settings = store.load_app_settings_summary().unwrap_or_default();
                        let connection_groups = config.groups.clone();
                        let connection_ssh_keys = store.list_ssh_keys().unwrap_or_default();
                        let connection_otp_entries = store.list_otp_entries().unwrap_or_default();
                        let connection_saved_passwords = store.list_passwords().unwrap_or_default();
                        let connection_saved_credentials =
                            store.list_credentials().unwrap_or_default();
                        let tunnels = store.list_tunnels().unwrap_or_default();
                        let tunnel_groups = store.list_tunnel_groups().unwrap_or_default();
                        let proxies = store.list_proxies().unwrap_or_default();
                        let proxy_groups = store.list_proxy_groups().unwrap_or_default();
                        let cloud_sync_settings =
                            store.load_cloud_sync_settings().unwrap_or_default();
                        let cloud_sync_state = store.load_cloud_sync_state().unwrap_or_default();
                        let translation_settings = store
                            .load_translation_settings()
                            .unwrap_or_else(|_| TranslationSettings {
                                target_language: settings.language.clone(),
                                ..TranslationSettings::default()
                            });
                        let quick_commands = store.load_quick_commands().unwrap_or_default();
                        let command_history = store.list_command_history(64).unwrap_or_default();
                        let keyword_highlights =
                            store.load_keyword_highlights().unwrap_or_default();
                        let ai_settings = store.load_ai_settings().unwrap_or_default();
                        let (ai_session_count, ai_message_count, ai_audit_count) =
                            ai_usage_counts(&store);
                        (
                            config.connections,
                            connection_groups,
                            connection_ssh_keys,
                            connection_otp_entries,
                            connection_saved_passwords,
                            connection_saved_credentials,
                            tunnels,
                            tunnel_groups,
                            proxies,
                            proxy_groups,
                            quick_commands.commands,
                            quick_commands.categories,
                            command_history,
                            keyword_highlights,
                            settings,
                            StoreStatus {
                                path,
                                message: "redb connection store online".to_string(),
                                ready: true,
                            },
                            cloud_sync_settings,
                            cloud_sync_state,
                            translation_settings,
                            ai_settings,
                            ai_session_count,
                            ai_message_count,
                            ai_audit_count,
                        )
                    }
                    Err(error) => (
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        KeywordHighlightConfig::default(),
                        AppSettingsSummary::default(),
                        StoreStatus {
                            path,
                            message: format!("failed to load sessions: {error}"),
                            ready: false,
                        },
                        CloudSyncSettings::default(),
                        CloudSyncState::default(),
                        TranslationSettings::default(),
                        AiSettings::default(),
                        0,
                        0,
                        0,
                    ),
                }
            }
            Err(error) => (
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                Vec::new(),
                KeywordHighlightConfig::default(),
                AppSettingsSummary::default(),
                StoreStatus {
                    path: runtime
                        .config_dir()
                        .join("nyaterm.redb")
                        .display()
                        .to_string(),
                    message: format!("failed to open store: {error}"),
                    ready: false,
                },
                CloudSyncSettings::default(),
                CloudSyncState::default(),
                TranslationSettings::default(),
                AiSettings::default(),
                0,
                0,
                0,
            ),
        };
        let otp_provider = Arc::new(NativeOtpProvider::new(
            runtime.config_dir().to_path_buf(),
            runtime.portable_key_path().map(ToOwned::to_owned),
        ));
        let transfer_duplicate_policy =
            SftpDuplicatePolicy::from_legacy_value(&settings.transfer_duplicate_strategy);
        let recording_manager = Arc::new(RecordingManager::new());
        recording_manager.set_memory_limit(settings.recording_memory_limit_bytes as usize);
        let cloud_sync_history = read_cloud_sync_history(
            runtime.log_dir(),
            settings.diagnostics_retention_days,
            CLOUD_SYNC_HISTORY_LIMIT,
        )
        .unwrap_or_default();
        let (ai_model_draft, ai_base_url_draft) = ai_active_profile_drafts(&ai_settings);
        let left_panel_width = settings.ui_left_panel_width as f32;
        let right_panel_width = settings.ui_right_panel_width as f32;
        let transfer_panel_height = settings.ui_transfer_height as f32;
        let active_left_panel = settings
            .ui_active_left_panel
            .as_deref()
            .and_then(NavItem::from_persistence_id)
            .filter(|item| item.is_left_panel())
            .or(Some(NavItem::Transfers));
        let active_right_panel = settings
            .ui_active_right_panel
            .as_deref()
            .and_then(NavItem::from_persistence_id)
            .filter(|item| item.is_right_panel())
            .or(Some(NavItem::Connections));
        let left_sidebar_collapsed = settings.ui_left_panel_collapsed;
        let right_inspector_collapsed = settings.ui_right_panel_collapsed;
        let security_secrets_unlocked = !settings.has_master_password;
        let activity_bar_layout = ActivityBarLayoutState {
            left_top: settings.ui_activity_bar_left_top.clone(),
            left_bottom: settings.ui_activity_bar_left_bottom.clone(),
            right_top: settings.ui_activity_bar_right_top.clone(),
            right_bottom: settings.ui_activity_bar_right_bottom.clone(),
            show_labels: settings.ui_activity_bar_show_labels,
        };
        let left_open_panels = settings.ui_left_open_panels.clone();
        let right_open_panels = settings.ui_right_open_panels.clone();
        let panel_stack_sizes = settings
            .ui_panel_stack_sizes
            .iter()
            .filter_map(|(key, value)| {
                (*value > 0).then(|| (key.clone(), (*value as f32) / 1000.))
            })
            .collect::<HashMap<_, _>>();
        let panel_multi_open = settings.ui_panel_multi_open;
        let translate_target_language = translation_settings.target_language.clone();

        Self {
            runtime,
            services: NativeServices::new(),
            inventory,
            connections,
            connection_search_draft: String::new(),
            connection_search_focus: cx.focus_handle(),
            connection_sort_mode: ConnectionSortMode::Default,
            connections_more_menu_open: false,
            connection_context_menu: None,
            connection_group_context_menu: None,
            hovered_connection_id: None,
            connection_details_tooltip_id: None,
            connection_drop_target: None,
            ai_execution_menu_open: false,
            hovered_connection_group_id: None,
            expanded_connection_groups: connection_groups
                .iter()
                .map(|group| group.id.clone())
                .collect(),
            connection_list_offset: 0,
            connection_groups,
            connection_editor: None,
            connection_editor_focus: cx.focus_handle(),
            connection_group_editor: None,
            connection_group_editor_focus: cx.focus_handle(),
            connection_delete_confirm: None,
            connection_group_delete_confirm: None,
            connection_ssh_keys,
            connection_otp_entries,
            connection_saved_passwords,
            connection_saved_credentials,
            connection_serial_ports: Vec::new(),
            tunnels,
            tunnel_groups,
            proxies,
            proxy_groups,
            network_tab: NetworkTab::Tunnels,
            network_delete_confirm: None,
            network_group_editor: None,
            network_group_delete_confirm: None,
            network_move_picker: None,
            network_expanded_sections: HashSet::new(),
            network_tunnel_editor: None,
            network_proxy_editor: None,
            network_group_editor_focus: cx.focus_handle(),
            network_tunnel_editor_focus: cx.focus_handle(),
            network_proxy_editor_focus: cx.focus_handle(),
            tunnel_search_draft: String::new(),
            tunnel_search_focus: cx.focus_handle(),
            proxy_search_draft: String::new(),
            proxy_search_focus: cx.focus_handle(),
            selected_connection_ids: HashSet::new(),
            last_selected_connection_id: None,
            quick_commands,
            quick_command_categories,
            quick_command_search_draft: String::new(),
            command_suggestions: None,
            command_input_tracker: TerminalInputState::new(),
            command_suggestions_suppressed: false,
            pending_command_history_entry: None,
            command_suggestion_search_gen: 0,
            credential_suggestions: None,
            credential_autofill_buffer: String::new(),
            credential_autofill_recent: HashMap::new(),
            credential_autofill_pending: None,
            credential_autofill_sending: false,
            credential_prompt_input_until_ms: 0,

            quick_command_search_focus: cx.focus_handle(),
            quick_command_selected_category: "all".to_string(),
            quick_command_sort_mode: quick_command_sort_mode_from_setting(
                &settings.ui_quick_cmd_sort_mode,
            ),
            quick_command_view_mode: quick_command_view_mode_from_setting(
                &settings.ui_quick_cmd_view_mode,
            ),
            quick_command_editor: None,
            quick_command_delete: None,
            quick_command_details: None,
            quick_command_category_delete: None,
            quick_command_category_rename: None,
            quick_command_variable_prompt: None,
            quick_command_import_dialog_open: false,
            quick_command_import_path_prompt: None,
            quick_command_editor_focus: cx.focus_handle(),
            quick_command_details_focus: cx.focus_handle(),
            quick_command_category_rename_focus: cx.focus_handle(),
            quick_command_variable_focus: cx.focus_handle(),
            quick_command_import_focus: cx.focus_handle(),
            command_history,
            session_command_history: HashMap::new(),
            command_search_draft: String::new(),
            command_search_focus: cx.focus_handle(),
            active_sessions_search_draft: String::new(),
            active_sessions_search_focus: cx.focus_handle(),
            active_session_menu_id: None,
            active_session_busy_actions: HashMap::new(),
            quick_switch_open: false,
            quick_switch_query: String::new(),
            quick_switch_selected_index: 0,
            quick_switch_focus: cx.focus_handle(),
            terminal_search_open: false,
            terminal_search_query: String::new(),
            terminal_search_focus: cx.focus_handle(),
            terminal_search_mode: TerminalSearchMode::Buffer,
            terminal_search_case_sensitive: false,
            terminal_search_regex: false,
            terminal_search_whole_word: false,
            terminal_search_active_index: 0,
            search_engine_edit_index: None,
            search_engine_expanded_index: None,
            search_engine_edit_field: SearchEngineEditorField::Name,
            search_engine_focus: cx.focus_handle(),
            terminal_scrollbar_dragging: false,
            terminal_actions_open: false,
            terminal_actions_focus: cx.focus_handle(),
            terminal_context_menu: None,
            action_link_menu: None,
            action_link_tooltip: None,
            action_link_hover_pending: None,
            translation_dialog: None,
            bottom_panel: BottomPanelMode::QuickCommands,
            send_command_draft: String::new(),
            send_command_focus: cx.focus_handle(),
            send_command_data_type: SendCommandDataType::Text,
            send_command_mode: SendCommandMode::Line,
            send_command_count: Some(1),
            send_command_interval_seconds: 1.0,
            send_command_line_ending: SendCommandLineEnding::Crlf,
            send_command_target: SendCommandTarget::Current,
            send_command_sending: false,
            send_command_cancel: None,
            send_command_progress_completed: 0,
            send_command_progress_total: 0,
            send_command_progress_round: 0,
            send_command_progress_rounds: 0,
            sync_groups: Vec::new(),
            sync_groups_open: false,
            sync_groups_focus: cx.focus_handle(),
            sync_groups_selected_id: None,
            broadcast_to_all: false,
            keyword_highlights,
            keyword_highlight_expanded_id: None,
            keyword_highlight_edit_id: None,
            keyword_highlight_edit_field: KeywordHighlightEditorField::Name,
            keyword_highlight_focus: cx.focus_handle(),
            settings,
            keybinding_recording_id: None,
            keybinding_pending_keys: None,
            keybinding_search_draft: String::new(),
            keybinding_search_focus: cx.focus_handle(),
            keybindings_focus: cx.focus_handle(),
            store_status,
            session_manager: Arc::new(SessionManager::new()),
            recording_manager,
            recording_search_draft: String::new(),
            recording_search_focus: cx.focus_handle(),
            session_start_tx,
            session_start_rx,
            tunnel_manager: Arc::new(SshTunnelManager::new()),
            tunnel_tx,
            tunnel_rx,
            pending_tunnels: Vec::new(),
            process_tx,
            process_rx,
            processes: Vec::new(),
            process_status: "ready".to_string(),
            process_pending: false,
            process_last_refresh_at: None,
            process_search_draft: String::new(),
            process_search_focus: cx.focus_handle(),
            process_sort_key: RemoteProcessSortKey::Cpu,
            process_sort_direction: RemoteProcessSortDirection::Descending,
            process_list_offset: 0,
            docker_list_offset: 0,
            docker_resource_list_offset: 0,
            send_command_hex_scroll_x: 0.,
            send_command_hex_scroll_y: 0.,
            process_selected_pid: None,
            process_menu_pid: None,
            process_nice_draft: "0".to_string(),
            process_nice_focus: cx.focus_handle(),
            process_signal_confirm: None,
            stats_tx,
            stats_rx,
            remote_stats: None,
            stats_status: "start an SSH session to inspect remote stats".to_string(),
            stats_pending: false,
            stats_last_refresh_at: None,
            stats_cpu_expanded: false,
            translate_tx,
            translate_rx,
            translate_provider: "google".to_string(),
            translation_settings,
            translation_secret_draft: TranslationSecretDraft::default(),
            translate_target_language,
            translate_input: String::new(),
            translate_result: None,
            translate_status: "Google translation ready".to_string(),
            translate_pending: false,
            translate_focus: cx.focus_handle(),
            translate_focused_field: TranslateInputField::Text,
            update_tx,
            update_rx,
            update_status: format!("Current version {}", env!("CARGO_PKG_VERSION")),
            update_info: None,
            update_pending: false,
            docker_tx,
            docker_rx,
            docker_overview: None,
            docker_status: "start an SSH session to inspect Docker".to_string(),
            docker_pending: false,
            docker_last_refresh_at: None,
            docker_logs: String::new(),
            docker_logs_container_id: None,
            docker_details: None,
            docker_details_container_id: None,
            docker_details_last_refresh_at: None,
            docker_confirm: None,
            docker_container_menu_id: None,
            docker_compose_menu_id: None,
            docker_tab: DockerTab::Containers,
            docker_search_draft: String::new(),
            docker_search_focus: cx.focus_handle(),
            docker_compose_expanded: HashSet::new(),
            docker_compose_services: HashMap::new(),
            docker_compose_service_errors: HashMap::new(),
            transfer_tx,
            transfer_rx,
            transfer_jobs: Vec::new(),
            transfer_selected_job_id: None,
            transfer_job_delete: None,
            transfer_remote_path: ".".to_string(),
            transfer_local_path: "nyaterm-download.bin".to_string(),
            transfer_duplicate_policy,
            transfer_path_prompt: None,
            transfer_browser_path: ".".to_string(),
            transfer_browser_home_dir: String::new(),
            transfer_browser_home_dir_pending: false,
            transfer_browser_path_draft: String::new(),
            transfer_browser_path_editing: false,
            transfer_browser_entries: Vec::new(),
            transfer_browser_status: "List a remote directory to browse files.".to_string(),
            transfer_browser_search: String::new(),
            transfer_browser_list_offset: 0,
            transfer_browser_search_expanded: false,
            transfer_browser_history: VecDeque::new(),
            transfer_browser_history_index: 0,
            transfer_browser_visited_history: VecDeque::new(),
            transfer_browser_session_cache: HashMap::new(),
            transfer_auto_sync_cwd_last_at: None,
            transfer_browser_favorites: VecDeque::new(),
            transfer_browser_sort_column: TransferBrowserSortColumn::Name,
            transfer_browser_sort_direction: TransferBrowserSortDirection::Ascending,
            transfer_browser_column_widths: TransferBrowserColumnWidths::default(),
            transfer_browser_column_resize: None,
            transfer_selected_remote_path: None,
            transfer_selected_remote_paths: HashSet::new(),
            transfer_browser_drag_selection: None,
            transfer_browser_pending_rename: None,
            transfer_browser_pending_rename_token: 0,
            transfer_browser_context_menu: None,
            transfer_browser_favorites_menu: None,
            transfer_browser_upload_menu: None,
            transfer_rename: None,
            transfer_rename_focus_pending: false,
            transfer_move: None,
            transfer_delete: None,
            transfer_new_folder: None,
            transfer_new_file: None,
            transfer_new_symlink: None,
            transfer_properties: None,
            transfer_editor: None,
            transfer_unknown_file: None,
            transfer_external_sync_prompt: None,
            transfer_external_always_uploads: HashSet::new(),
            recording_path_prompt: None,
            config_path_prompt: None,
            diagnostics_path_prompt: None,
            keyword_highlight_path_prompt: None,
            active_snapshot_password_prompt: None,
            cloud_sync_settings,
            cloud_sync_state,
            cloud_sync_history,
            cloud_sync_history_expanded: HashSet::new(),
            cloud_sync_conflict: None,
            cloud_sync_secret_draft: CloudSyncSecretDraft::default(),
            cloud_sync_status: "local provider ready".to_string(),
            cloud_sync_focus: cx.focus_handle(),
            cloud_sync_focused_field: CloudSyncInputField::RemoteRoot,
            ai_settings,
            ai_model_draft,
            ai_base_url_draft,
            ai_secret_draft: String::new(),
            ai_status: "AI settings ready".to_string(),
            ai_session_count,
            ai_message_count,
            ai_audit_count,
            ai_discovery_tx,
            ai_discovery_rx,
            ai_discovery_pending: false,
            ai_chat_tx,
            ai_chat_rx,
            ai_chat_pending: false,
            ai_chat_job_id: 0,
            ai_chat_cancel: None,
            ai_chat_session_id: format!("ai-session-{}", uuid()),
            ai_prompt_draft: String::new(),
            ai_prepared_request: None,
            ai_response_preview: "Ask mode ready".to_string(),
            ai_chat_messages: Vec::new(),
            ai_streaming_assistant_id: None,
            ai_history_open: false,
            ai_history_query: String::new(),
            ai_history_search_focus: cx.focus_handle(),
            ai_sessions: Vec::new(),
            ai_command_cards: Vec::new(),
            ai_agent_task_prompt: None,
            ai_agent_step_index: 0,
            ai_agent_loop: None,
            ai_agent_capture: AgentOutputCaptureProcessor::new(),
            ai_agent_steps: Vec::new(),
            ai_agent_thought_expanded: HashSet::new(),
            ai_agent_output_expanded: HashSet::new(),
            ai_chat_focus: cx.focus_handle(),
            ai_chat_focus_pending: false,
            ai_focus: cx.focus_handle(),
            ai_focused_field: AiInputField::Model,
            ai_action_expanded: None,
            ai_action_edit: None,
            ai_action_focus: cx.focus_handle(),
            ai_model_collapsed_groups: HashSet::new(),
            ai_manual_model_drafts: HashMap::new(),
            ai_manual_model_focus: cx.focus_handle(),
            ai_manual_model_edit_group: None,
            ai_credential_expanded_id: None,
            ai_credential_edit: None,
            ai_credential_focus: cx.focus_handle(),
            ai_credential_secret_drafts: HashMap::new(),
            transfer_focus: cx.focus_handle(),
            transfer_queue_focus: cx.focus_handle(),
            transfer_browser_focus: cx.focus_handle(),
            transfer_browser_path_focus: cx.focus_handle(),
            transfer_browser_search_focus: cx.focus_handle(),
            transfer_rename_focus: cx.focus_handle(),
            transfer_move_focus: cx.focus_handle(),
            transfer_delete_focus: cx.focus_handle(),
            transfer_new_folder_focus: cx.focus_handle(),
            transfer_new_file_focus: cx.focus_handle(),
            transfer_new_symlink_focus: cx.focus_handle(),
            transfer_properties_focus: cx.focus_handle(),
            transfer_editor_focus: cx.focus_handle(),
            transfer_unknown_file_focus: cx.focus_handle(),
            transfer_external_sync_focus: cx.focus_handle(),
            transfer_job_delete_focus: cx.focus_handle(),
            transfer_default_editor_focus: cx.focus_handle(),
            transfer_focused_field: TransferInputField::Remote,
            duplicate_prompts: Arc::new(SftpDuplicatePromptBroker::default()),
            active_duplicate_prompt: None,
            pending_session_name: None,
            pending_ssh_config: None,
            pending_ai_execution_profile: AiExecutionProfile::SendOnly,
            pending_session_custom_name: None,
            pending_session_tab_color: None,
            pending_session_after_id: None,
            pending_session_insert_index: None,
            pending_terminal_seed_output: None,
            pending_reconnect_replace_id: None,
            pending_startup_command: None,
            pending_session_multiplex_key: None,
            pending_source_connection_id: None,
            pending_workspace_split: None,
            host_key_prompts: Arc::new(HostKeyPromptBroker::default()),
            active_host_key_prompt: None,
            credential_prompts: Arc::new(CredentialPromptBroker::default()),
            active_credential_prompt: None,
            credential_focus: cx.focus_handle(),
            snapshot_password_focus: cx.focus_handle(),
            otp_provider,
            active_session_id: None,
            active_ssh_config: None,
            active_ai_execution_profile: AiExecutionProfile::SendOnly,
            session_order: Vec::new(),
            session_metadata: HashMap::new(),
            session_custom_names: HashMap::new(),
            session_dynamic_titles: HashMap::new(),
            session_cwds: HashMap::new(),
            zmodem_sessions: HashMap::new(),
            session_tab_colors: HashMap::new(),
            ssh_multiplex_handles: HashMap::new(),
            terminal_views: HashMap::new(),
            tab_actions_session_id: None,
            tab_actions_anchor: None,
            tab_actions_focus: cx.focus_handle(),
            close_all_sessions_confirm_open: false,
            pending_quit_after_close_all: false,
            pending_window_quit: false,
            close_all_sessions_confirm_focus: cx.focus_handle(),
            rename_session_id: None,
            rename_draft: String::new(),
            rename_focus: cx.focus_handle(),
            color_picker_open: false,
            color_picker_focus: cx.focus_handle(),
            session_info_open: false,
            session_info_focus: cx.focus_handle(),
            startup_command_open: false,
            startup_command_action: StartupCommandAction::Duplicate,
            startup_command_draft: String::new(),
            startup_command_delay_ms: DEFAULT_DUPLICATE_STARTUP_DELAY_MS,
            startup_command_focus: cx.focus_handle(),
            temporary_ssh_link_open: false,
            temporary_ssh_link_draft: String::new(),
            temporary_ssh_link_error: None,
            temporary_ssh_link_focus: cx.focus_handle(),
            multi_line_paste: None,
            multi_line_paste_focus: cx.focus_handle(),
            terminal_focus: cx.focus_handle(),
            lock_focus: cx.focus_handle(),
            lock_password_draft: String::new(),
            lock_status: String::new(),
            terminal_output: String::from(INITIAL_TERMINAL_BANNER),
            terminal_screen: initial_terminal_screen(),
            terminal_scroll_offset: 0,
            terminal_status: "idle".to_string(),
            event_pump_started: false,
            cursor_blink_on: true,
            cursor_blink_tick: 0,
            terminal_selection: None,
            terminal_selection_dragging: false,
            terminal_surface_bounds: None,
            terminal_cell_metrics: None,
            visual_bell_ticks: 0,
            terminal_file_drop_hover: None,
            last_viewport_size: (1280., 800.),
            selected_nav: NavItem::Workspace,
            main_mode: MainMode::Workspace,
            settings_active_tab: SettingsTab::General,
            active_left_panel,
            active_right_panel,
            left_open_panels,
            right_open_panels,
            panel_stack_sizes,
            panel_multi_open,
            right_focus: RightFocus::Default,
            left_sidebar_collapsed,
            right_inspector_collapsed,
            left_panel_width,
            right_panel_width,
            transfer_panel_height,
            panel_resize: None,
            transfer_height_resize: None,
            panel_stack_resize: None,
            activity_bar_layout,
            activity_bar_context_menu: None,
            title_menu_open: None,
            open_tabs_menu_open: false,
            new_session_menu_open: false,
            session_tab_strip_scroll: ScrollHandle::new(),
            session_tab_scroll_into_view_pending: false,
            last_connect_failure_name: None,
            last_connect_failure_error: None,
            security_auth_tab: SecurityAuthTab::Keys,
            security_key_editor: None,
            security_key_editor_focus: cx.focus_handle(),
            security_otp_editor: None,
            security_otp_editor_focus: cx.focus_handle(),
            security_password_editor: None,
            security_password_editor_focus: cx.focus_handle(),
            security_credential_editor: None,
            security_credential_editor_focus: cx.focus_handle(),
            security_delete_confirm: None,
            security_otp_codes: HashMap::new(),
            security_revealed_passwords: HashMap::new(),
            security_revealed_credentials: HashMap::new(),
            security_status: "security ready".to_string(),
            security_secrets_unlocked,
            security_unlock_prompt_open: false,
            security_unlock_draft: String::new(),
            security_unlock_error: None,
            security_unlock_focus: cx.focus_handle(),
            workspace_split: None,
            workspace_split_resize: None,
            session_pane_roots: HashMap::new(),
            session_tab_owner: HashMap::new(),
            terminal_windows: None,
            focused_terminal_window_leaf_id: None,
            terminal_window_drop: None,
            terminal_windows_restored: false,
            workspace_pane_layout_restored: false,
            open_tabs_restored: false,
            startup_restore_complete: false,
            startup_restore_queue: Vec::new(),
            startup_pending_pane_layouts: Vec::new(),
            startup_pending_active_pane_indexes: Vec::new(),
            is_locked: false,
            last_user_activity_at: Instant::now(),
        }
    }
}
